### ISSUE TITLE
get status of a pipeline after some nodes has finished 

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#10]
look at the next get status response:

{
    "jobId":"apak-batch:ec876a23-079a-4286-a0cb-20f9ecb50774",
    "timestamp":"2018-01-28T13:05:16.538Z",
    "pipeline":"apak-batch",
    "data":
    {
        "level":"debug",
        "status":"active",
        "progress":"50.00",
        "details":**"50.00% completed, 2 active, 2 succeed",**
        "activeNodes":
        [
            {
                "nodeName":"apak",
                "algorithmName":"red-alg",
                "batch":
                {
                    **"active":4,
                    "total":4**
                }
            }
        ]
    }
}

as you can see, in the details, 2 nodes already completed and 2 other are still running, but in batch, it shows that there are still 4 active nodes.

**Comment by NassiHarel** [comment]
We decided that active (inside activeNodes -> batch) is the sum of: succeed + failed + active

**Comment by eytangro** [comment]
isn't succeed + failed + active =total?
which this already there?

**Comment by NassiHarel** [comment]
No, there are also creating and pending.

**Comment by NassiHarel** [comment]
Like this:

```js
"details": "33.33% completed, 4 succeed, 2 active, 4 pending, 2 creating",
"activeNodes": [
{
        "nodeName": "green",
        "algorithmName": "green-alg",
        "batch": {
              "active": 6,
               "total": 10
             }
        }
]
```

**Comment by eytangro** [comment]
ok closed
