### ISSUE TITLE
Fail to execute "Run Node" 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1016]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
Fail to execute "Run Node" the job stay in "active" mode 
when trying to "run node" on Simple pipeline on the yellow node
the following  Pipeline Driver errors appear:
1. unable to find watcher for /jobs/tasks/main:simple:pn15aa8d/
2. unable to stop pipeline, Cannot read property '_getNodesAsFlat' of null
3. node "yellow" is depend on node "green" which is not exists

**Comment by NassiHarel** [comment]
@tamir321 

Actually, this is one bug that created a chain reaction: 
`node "yellow" is depend on node "green" which is not exists`.
Just a Bug in the DAG :-)

Fixed

**Comment by tamir321** [comment]
tested on version 
systemVersion: "v2.0.16",
fullSystemVersion: "v2.0.16-1605190942320",
