### ISSUE TITLE
View statistics of pipeline requests' amount in a graph view

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#103]
As a HKube manager I want to be able to view statistics of pipeline requests amount in a graph view, so that I can analyze the resources allocation mechanism and sizing of system resources over time.

**User Story implementation details:**
1. Statistics of pipeline requests amount means: amount of pipeline requests per minute 
2. Each of the statistics information will be calculated separately per pipeline type.
3. Graph view is detailed in #102

**Comment by eytangro** [comment]
TID-206

**Comment by eytangro** [comment]
TID-206
