### ISSUE TITLE
View statistics of pipeline's pending requests in a graph view

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#104]
As a HKube manager I want to be able to view statistics of pipeline's pending requests in a graph view, so that I can analyze the resources allocation mechanism and sizing of system resources over time.

**User Story implementation details:**
1. Statistics of pipeline's pending requests means: amount of pipeline's pending (state = pending) requests per minute 
2. Each of the statistics information will be calculated separately per pipeline type.
3. Graph view is detailed in #102

**Comment by eytangro** [comment]
TID-206
