### ISSUE TITLE
streaming scale issues

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#1053]
- [ ] on scaling down - stop stateless workers, instead of exit.
- [ ] In case that stateless workers got a job too late, and they are un-needed anymore, they will listen forever.....................
need to scale-down also stateless workers that don't receive any data for X time and don't have any sender.
- [ ] in case there are multiple senders with the same NodeName, we need to separate statistics.

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.0.123",
fullSystemVersion: "v2.0.123-1617290919960",
