### ISSUE TITLE
Monitor handling time of algorithm request

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#106]
As a Pipeline Builder/ HKube manager I want to be able to view the average handling time of algorithm's requests in configurable time frame, so that I can analyze the performance of algorithm execution.
---
**User Story implementation details:**
1. _Handling time of algorithm's requests_ - from the time the initialization of the algorithm execution was completed till the time the result of the algorithm was written.
2. Statistics of algorithm request's handling time  - 50 & 90 percentile of algorithm request's handling time 
3. Each of the statistics information will be calculated separately peralgorithm type.
4. Graph view is detailed in #110

**Comment by eytangro** [comment]
TID-201

**Comment by eytangro** [comment]
TID-205
