### ISSUE TITLE
Allow to ignore files in hkubectl build

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#1078]
**Is your feature request related to a problem? Please describe.**
Currently when building an algorithm with the cli it is not possible to ignore (exclude) files from the .zip file
**Describe the solution you'd like**
Add a way to ignore files when creating the .zip file for the algorithm

**Comment by yehiyam** [comment]
Implemented in kube-HPC/hkubectl#24

Added support for `.hkubeignore` file.
The file is similar to `.gitignore`. 
When the file is present, the glob patterns in the file are ignored.
e.g.
```
node_modules
.git
```
Will ignore `node_modules` and `.git` folders

Additional info:
1. nested `.hkubeignore` files are supported. 
2. python and nodejs templates include a default ignore file: `__pycache` for python and `node_modules` for nodejs, and `.git` for all

**Comment by yehiyam** [comment]
Included in version [v1.1.162](https://github.com/kube-HPC/hkubectl/releases/tag/v1.1.62)

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.0.146",
fullSystemVersion: "v2.0.146-1619609937254",

automation test added to file cliTests
it = 'sync python alg ignor files'
