### ISSUE TITLE
View statistical information of algorithm requests in a graph view

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#110]
As a Pipeline Builder/ HKube manager I want to be able to view statistical information of  algorithm's requests in a few graph views (one graph per information type), so that I can analyze the performance of multiple types of algorithms over time.

**User Story implementation details:**
1. The information to be displayed in the graph view will be detailed in other user stories.
2. The user will be able to filter the information displayed in all the graphs by time frame.
3. The user will be able to filter the information displayed in all the graphs by algorithm types (multiple choice/ all).
3. The user will be able to choose the pipeline types (multiple choice/ all) for the information displayed in all the graphs.
4. The statistical information will be displayed in separate line per algorithm type.

**Comment by eytangro** [comment]
TID-205
