### ISSUE TITLE
UI :LOG from elastic displays the first 500 rows

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1100]
if the log is bigger than 500 rows:
- [ ] display the last 500 rows
- [ ] inform the user that it is a partial log
- [ ] enable the user receives the non-display logs  

Log issues are concentrated at [Make tasks(algorithm runs) logs more accessible](https://github.com/kube-HPC/hkube/issues/1636)
Closeing

**Comment by maty21** [comment]
will fix under job search api #1446
