### ISSUE TITLE
GPU ICON disappears when changing algorithm GPU consumption: 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1114]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
GPU ICON disappears when changing algorithm GPU consumption: 
can work the opposite way and display more GPU than the system have
![image.png](https://images.zenhubusercontent.com/5ddb91c470bd590001fbdfae/8d5f9850-1bd0-4f94-a75c-6c0c5e95689f) 

**Expected behavior**

**To Reproduce**
Create an algorithm that needs GPU with nonexisting Image 
While the algorithm is trying to run (image pull back-off) change the algorithm and remove the GPU 
The GPU icon disappears from HKUBE
When the algorithm execution will end or terminated the icon will return

**Comment by yehiyam** [comment]
clean `ImagePullError` containers
fixed with https://github.com/kube-HPC/clean-old-jobs/pull/14

**Comment by yehiyam** [comment]
related to https://github.com/kube-HPC/hkube/issues/1120

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.0.128",
fullSystemVersion: "v2.0.128-1618153188549",
