### ISSUE TITLE
View statistics of algorithm's pending requests in a graph view

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#112]
As a HKube manager I want to be able to view statistics of algorithm's pending requests in a graph view, so that I can analyze the resources allocation mechanism and sizing of system resources over time.

**User Story implementation details:**
1. Statistics of algorithm's pending requests means: amount of algorithm's pending (state = pending) requests per minute 
2. Each of the statistics information will be calculated separately per algorithm type.
3. Graph view is detailed in #110

**Comment by eytangro** [comment]
TID-205
