### ISSUE TITLE
pipeline execution option should be merged with the pipeline original option 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1125]
**Describe the bug**
pipeline execution option should be merged with the pipeline original option
if executing  pipeline with partial options it overwrites the pipeline original options with defaults 

**To Reproduce**
change "simple" pipeline ttl to 600

execute simple pipeline without ttl

```json
{
    "name": "simple",
    "flowInput": {
        "files": {
            "link": "links-1"
        }
    },
    "options": {

        "progressVerbosityLevel": "debug"
    },
    "priority": 3
}
```
the pipeline will be executed with ttl 3600 (the default )

**Comment by NassiHarel** [comment]
This issue probably created after #716  issue

**Comment by NassiHarel** [comment]
@tamir321 
I just upgraded the api-server version

**Comment by NassiHarel** [comment]
@tamir321
Done

**Comment by tamir321** [comment]
Tested on systemVersion: "v2.0.128",
fullSystemVersion: "v2.0.128-1618153188549",
