### ISSUE TITLE
Version 2.0 UI issues

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1143]
- [ ] Error logs display has horizontal scroll bar, and the timestamp is clipped 
- [ ]  flowInput (and probably all of the fields) is not used from the run pipeline drawer
- [ ]  Workers table: Only one worker details line is shown
- [ ] Download result does not work (its downloading html)
- [ ] in a active job there should be a pause button not play (when click it should be changed to play)
- [ ]

**Comment by reggev** [comment]
Can you please move those issues to here: https://github.com/kube-HPC/simulator/issues
