### ISSUE TITLE
Display HW usage information in a few graph views

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#115]
As a Pipeline Builder/ HKube manager I want to be able to view HW usage information in a few graph views (one graph per information type), so that I can analyze HW overload and sizing over time.
---
**User story implementation details:**
1. The information to be displayed in the graph view will be detailed in other user stories.
2. The user will be able to filter the information displayed in all the graphs by time frame.
3. The information will be displayed per container using the container name.
4. The user will be able to filter the information displayed in all the graphs by choosing specific container .

**Comment by eytangro** [comment]
TID-201
