### ISSUE TITLE
Firefox displays log line as 2 lines

### ISSUE THREAD

**Issue by mattanf2** [kube-HPC/hkube#1165]
In Firefox webbrowser log lines are displayed in 2 lines where the second line contains only 1 word (see image)

**To Reproduce**
1. Open firefox
2. Go to dashboard
3. Open any job with the "..." icon
4. Look at logs 
![2log_lines](https://user-images.githubusercontent.com/18640840/109658949-d5979700-7b6f-11eb-9754-5c7117cfbb97.png)

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.1.42",
fullSystemVersion: "v2.1.42-1624977220317",
