### ISSUE TITLE
Make algorithm loading errors visible in dashboard

### ISSUE THREAD

**Issue by mattanf2** [kube-HPC/hkube#1168]
Hkube does not clearly state in the UI problems it has running algorithms: 
1. If an algorithm fails to load, for instance, due to its image missing, I can only identify that problem by looking at kubernetes directly. All the dashboard says is that the algorithm is pending and after an hour the pipeline switches to stop.
2. In another example, if an algorithm fails to load because there aren't any computers with enough resources to execute it. There is no indication of the problem besides the pipeline moving to "pending".

Please add indication in the dashboard for such problems so they can be more easily identified

**Comment by tamir321** [comment]
tested on
systemVersion: "v2.3.18",
fullSystemVersion: "v2.3.18-1648462268639",
