### ISSUE TITLE
View RAM usage information in a graph view

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#117]
As a HKube manager I want to be able to view RAM usage information in a graph view, so that I can analyze RAM usage and sizing over time.
---
**User story implementation details:**
1. _RAM usage  information means: _
1.1. Average RAM usage (percentage) per minute in the chosen time frame. The average RAM usage will be calculated separately per container. 
1.2. Total (cluster) RAM usage (percentage) in the chosen time frame.
2. General requirements for graph view are detailed in #115

**Comment by eytangro** [comment]
TID-201
