### ISSUE TITLE
Pipeline with conditional algorithms (if statements)

### ISSUE THREAD

**Issue by mattanf2** [kube-HPC/hkube#1173]
I have cases where I have pipelines with algorithms that may or may not need to run depending on the input of another algorithm. 
The way that I currently solve this is by defining those algorithms to run in a batch then either supplying an input array of 1 or an input array of 0. This is problematic for 2 reasons: 
1. Its ocward to write
2. In a lot of cases I don't need to run the algorithm in the "if statement" but hkube loads to as a pod anyway.

A more straight forward notation of "run algo if input exists" would be better, It would also help If I could state whether the algorithm would run most times to tell hkube whether it should preload the algorithm or not.

**Comment by maty21** [comment]
after thinking we decided that it's not something that we want to add  to the current roadmap
