### ISSUE TITLE
Pipeline fail with taksId error

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1176]
**HKube micro-service**
Wrapper

**Describe the bug**
algorithm completed secssfuly but the wrapper returns a "TaskId" as an error to the worker

**Comment by yehiyam** [comment]
Integrated in wrapper version 2.0.34 and hkube 1.3.162

**Comment by yehiyam** [comment]
Also fixed in master

**Comment by tamir321** [comment]
was fix on customer site

**Comment by tamir321** [comment]
was fix on customer site
