### ISSUE TITLE
View storage usage information in a graph view

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#118]
As a HKube manager I want to be able to view storage usage information in a graph view, so that I can analyze storage usage and sizing over time.
---
**User story implementation details:**
1. _storage usage  information means: _
1.1. Average storage usage (percentage) per minute in the chosen time frame. The average storage usage will be calculated separately per container. 
1.2. Total (cluster) storage usage (percentage) in the chosen time frame.
2. General requirements for graph view are detailed in #116

**Comment by eytangro** [comment]
TID-201
