### ISSUE TITLE
Add ability to filter out pending jobs (part feature, part bug)

### ISSUE THREAD

**Issue by mattanf2** [kube-HPC/hkube#1186]
When we run A big scenario against hkube (hkube_qa), hkube can get filled with jobs to the point where It only has room to display pending jobs. In the current scenario there are 500 jobs. The UI can only display the first 100 or so

There needs to be a way to see all the non-pending jobs
It will also be helpfull to be able to filter by status. 

I have currently been waiting for a couple of hours not realizing the system was stuck because I assumed that hkube was handling jobs not in the UI.

Also given the limitation of 100 jobs it will also be a good idea to provide perhaps some sort of pagination interface or an ability to choose the amount of jobs displayed in the UI.

**Comment by maty21** [comment]
will fix in job search api   #1446
