### ISSUE TITLE
start_algorithm() does not support binary data in the same way binary data moves within a pipeline

### ISSUE THREAD

**Issue by mattanf2** [kube-HPC/hkube#1188]
Detected on version 1.3.160

How to recreate:
1. Create 2 algorithms
2. Create a pipeline around one of the algorithms
3. Have the first algorithm call the second algorithm through the start_algorithm() function of the api object sent through the start function
If the data sent contain binary data then the second algorithm receives either None or an array of bytes instead of the original byte string, dependent on how algorithm a was called (debug or regular).

It would be nice in the start_algorithm would support binary data. If not, at least issue a warning when binary data is supplied through the input argument of the function.

**Comment by yehiyam** [comment]
to be fixed/tested in 
- [ ]  python
1. fixed by https://github.com/kube-HPC/hkube/pull/1193 and https://github.com/kube-HPC/python-wrapper.hkube/pull/71
- [ ] nodejs
- [ ] java

**Comment by tamir321** [comment]
Tested on 
systemVersion: "v2.0.142",
fullSystemVersion: "v2.0.142-1619078464804",

**Comment by tamir321** [comment]
Tested on 
systemVersion: "v2.0.142",
fullSystemVersion: "v2.0.142-1619078464804",
