### ISSUE TITLE
Swagger api /pipeline/results and /pipeline/status limit their responces to 1000 jobs

### ISSUE THREAD

**Issue by mattanf2** [kube-HPC/hkube#1190]
api /pipeline/results and /pipeline/status limit their responses to 1000 jobs

We have runs that are way more than 1000 jobs. This limits our ability to debug our runs

True as of 1.3.160v

**Comment by yehiyam** [comment]
fixed by #1200

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.3.18",
fullSystemVersion: "v2.3.18-1648462268639",
