### ISSUE TITLE
results of a pipeline comes with a big delay

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#12]
if i run a big pipeline, i check the status every couple of seconds, as soon as i get status: completed
i ask for the result of the pipeline/
sometimes i get the right result and sometimes i get that the results are not still aviliable and it can take up to several minutes until they are.

as a user i would like to ask for the results as soon as i ask them. without a delay

**Comment by NassiHarel** [comment]
There is a delay in the all cluster

**Comment by eytangro** [comment]
seems to be resolved for now
