### ISSUE TITLE
Add ability to limit the number of runs per pod

### ISSUE THREAD

**Issue by mattanf2** [kube-HPC/hkube#1206]
I have a algorithm that if it is run enough times within the same pod terminates terminates with an exception due to a memory leak.
I will try to fix the memory leak. 

However as a precaution I would like the ability to set a maximum amount of times that a task can ran within a pod before the pod is removed and a new one is created instead.

**Comment by maty21** [comment]
it was investigated with @mattanf2 and decided not to Implement it
