### ISSUE TITLE
Streaming Gateway

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#1233]
- [x] update pipeline node descriptor - Api-Server - (@golanha)
- [x] add api for get gateways/jobId - Api-Server - (@golanha)
- [x] add new collection - mongo.db (@golanha)
- [x] create, delete and validate gateway using Mongo on start/stop pipeline - Api-Server - (@NassiHarel)
- [x] make gateway kind stateful by default - Api-Server - (@NassiHarel)
- [x] create and delete gateway service+ingress on start/stop pipeline - Algorithm-Operator - (@NassiHarel)
- [x] new lib that includes the wrapper with our stateful algorithm and rest server - (@NassiHarel)
- [x] add cleaner for gateways - (@golanha)
- [ ] Implement UI, add swagger link - (@?)

https://docs.google.com/presentation/d/1GklGHKuofoadK0wbVafsf4HO-FY7hbnUQlW-M7Fs_28/edit?usp=sharing

```
{
    "name": "gateway-test",
    "kind":"stream",
    "nodes": [
        {
            "nodeName": "A",
            "kind": "gateway",
            "spec": {
               "name": "images-gateway",
               "description": "images streaming source",
               "cpu": 1,
               "mem": "1Gi"
            }
        },
        {
            "nodeName": "B",
            "algorithmName": "green-alg",
            "input": [ {"delay": 0.01}]
        }
    ],
     "streaming": {
        "flows": {
            "analyze": "A >> B"
        }
    }
}
```

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.1.88",
fullSystemVersion: "v2.1.88-1631616917808",
