### ISSUE TITLE
Update jeager-client in hkube_python_wrapper

### ISSUE THREAD

**Issue by mattanf2** [kube-HPC/hkube#1241]
hkube_python_wrapper package requires the package jeager-client==4.0.0
jeager-client==4.0.0 requires package tornado<5 
This creates dependency conflict with other packages (in my case streamlit)
please update jeager-client to a higher version. 

P.S. 
I don't know which version removed the "tornado<5 " specification. but there was a  change in code to jeager-client that removed it about 2 years ago

**Comment by yehiyam** [comment]
fixed in https://github.com/kube-HPC/python-wrapper.hkube/pull/76
```
'jaeger-client==4.0.0; python_version < "3.2.0"',
'jaeger-client>=4.4.0; python_version >= "3.2.0"'
```
