### ISSUE TITLE
Debug algorithm

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#1246]
- [x] debug algorithm from algorithm list
- [x] debug algorithm from pipeline list
- [x] debug algorithm from pipeline graph

- [x] re Run node in debug mode
An option to re run a node from a previous job in debug mode (from the Debug socket list)
so that we could debug locally an algorithm that ran in the hkube with the same input

**Comment by tamir321** [comment]
tested on version 2.1
