### ISSUE TITLE
resource executor meeting  status 

### ISSUE THREAD

**Issue by maty21** [kube-HPC/hkube#125]
- [ ] add API to kuberntes in order to know what is the available resources 
- [x] add API for understanding worker status (idle, running) 
- [ ] add logic that moves 'hot' worker to idle mode (cant get new jobs, decreasing exit timeout) 
      by using ETCD
- [ ] set resource k8s job limit for the average user settings
- [ ] set scheduled resource to something that lower(maybe divide bt 2) than the limit

*  on storing new algorithms user will have to set average hardware usage

**Comment by NassiHarel** [comment]
the motivation under "stopping worker for getting new job " is that there is a methodical issue in the current pattern .  for example algorithm x with tasks that in the current state have  highest score 50 but already have hot workers will still get jobs before other algorithms with higher priority
