### ISSUE TITLE
jager missing data

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1285]
**HKube micro-service**
pipeline driver

**Describe the bug**
when executong pipeline the jager chart is missing algorithim data 
![image.png](https://images.zenhubusercontent.com/5ddb91c470bd590001fbdfae/910452aa-81ec-456c-91de-22632ee01fb9)
 it should containg algorithms start

**Comment by tamir321** [comment]
tested on:

systemVersion: "v2.1.40",
fullSystemVersion: "v2.1.40-1624865396771",
versions: [
{
project: "api-server",
tag: "v2.1.17",
image: "hkube/api-server"
},

**Comment by NassiHarel** [comment]
@yehiyam @tamir321 

I wonder how this bug resolved by itself, I didn't do anything
