### ISSUE TITLE
hkubectl - watch and sync a- algorithm fail to reconnect to worker

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1286]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
hkubectl - watch and sync a- algorithm fail to reconnect to worker

**To Reproduce**
execute :

-  hkubectl sync create --entryPoint main.py --algorithmName <algorithim name> --folder <folder name> --env python

-   kubectl sync watch -a <algorithim name> -f <folder name>

- run the algorithm - should complete secssfuly 

- change the main.py  (the code was chage in the pod)

- rerun the algorithm  - the algorithm stay in active mode  and never excuted

**Comment by yehiyam** [comment]
duplicate of #1314
