### ISSUE TITLE
Add config for api-server max payload size

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#1289]
- [x] Add config option for maxPayloadLimit
- [x] Set rest API max size 
- [x] Fix hkubectl upload limit
- [x] Add parameter to helm

**Comment by yehiyam** [comment]
1,2 fixed by #1288 
3 fixed by kube-HPC/hkubectl#34

**Comment by yehiyam** [comment]
4 fixed by kube-hpc/helm#43

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.1.42",
fullSystemVersion: "v2.1.42-1624977220317",
