### ISSUE TITLE
DVC client fails to move files

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1299]
**HKube micro-service**
datasource-service
**Describe the bug**
DVC client fails to move files
In dvc versions 2.2 and 2.3 there is a bug that when moving a file the .meta field is not copied to the new .dvc file 
the bug is in the new DVC client code

**To Reproduce**
Reproduced in unit test `should move a file`

**Comment by yehiyam** [comment]
should be ok when iterative/dvc#6200 is fixed

**Comment by yehiyam** [comment]
temp fix (pin dvc version to 2.1) #1302
