### ISSUE TITLE
pipelines that sometimes do not end the run (inconsistent)

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#13]
i have a pipeline with eval.
some of the times i run the tests (batch of 1000 inputs) and get the results pretty quick without problems.
other times i run the same pipeline and it wont end running i sometimes wait for 10-30 minutes without any results and the status shows only pending and completed without active pods running.

**Comment by eytangro** [comment]
seems to be resolved for now

**Comment by NassiHarel** [comment]
@maty21  the status stays in active but  its seems like that there is no other side effects

**Comment by eytangro** [comment]
didn't see that in the last tests i ran
