### ISSUE TITLE
Merge swaggers

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#1308]
- [x] Expose only one swagger in the api-server.

Remove duplicate swagger from:
- [x] gc-service
- [x] dataSources

Create a main swagger file that will be used by all services for validation:
- [x] api-server
- [x] gc-service
- [x] dataSources

**Comment by tamir321** [comment]
tested on version
systemVersion: "v2.1.53",
fullSystemVersion: "v2.1.53-1626181128494",
