### ISSUE TITLE
The remove of Debug ingress and service needs to be delayed

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1311]
Currently when the job running a debug algorithm ends, the debug algorithm is removed from db, as a result the algorithm operator deletes the ingress and service exposing the debug algorithm pod. This results in a poor user experience since it takes time for the debug session to connect again, getting http 503/404 errors. 
The removal of the ingress and service needs to be delayed, if it stays as long as the created algorithm pod, it might be sufficient to deliver a smooth experience when debugging several times.

**Comment by yehiyam** [comment]
Fixed by #1321
