### ISSUE TITLE
pipeline versions 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1315]
As a user, I would like to have the option to create the pipeline version that includes:
- algorithms version
- the pipeline description

when execute the result will include the pipeline version

the pipeline should have a similar UI as the algorithm that enables changing the current version

changing the pipeline's current version to a different version will change the algorithm's current version according to the pipeline version. 

pipeline version should not be mandatory 

- a user can frizz the current version or change to an older version 

- if the user did not create a  pipeline version or made changes after the last version the latest version will be used

attempt to delete algorithm version that is tied to pipeline version will raise an error
attempt to change pipeline version  that is tied to a running pipeline will raise an error

**Comment by maty21** [comment]
dup of #1072
