### ISSUE TITLE
Support maxWorkers for algorithm

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#1323]
**Is your feature request related to a problem? Please describe.**
Hkube should support specifying the maximum number of workers for an algorithm.
This is  needed for debug and gateway types
**Describe the solution you'd like**

- [x] Add `maxWorkers` property to algorithm definition in swagger and api-server
- [x] Add support in task-executor to create up to the `maxWorkers` workers for the algorithm

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.1.54",
fullSystemVersion: "v2.1.54-1626879030874",
