### ISSUE TITLE
unable to re-run cached pipeline

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#1325]
**Describe the bug**
When clicking the "re-run" button on a job for a cached execution, the pipeline will not run

**Expected behavior**
The pipeline should run again

**To Reproduce**
1. Run `simple` pipeline
2. Run cached (node) from yellow node
3. After cached job has finished click re-run

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.1.53",
fullSystemVersion: "v2.1.53-1626181128494",
