### ISSUE TITLE
Job search API

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#1337]
1.1.	Goal: Enable the user to filter pipeline's executions for better investigation of bugs and  performance issues
1.2.	Hkube shall enable the user to filter pipeline's executions by:
•	Time
•	Kind of Pipeline
•	Status of Pipeline
1.3.	Hkube shall enable the user to mark/ Unmark pipeline's execution data  for latter usage. 
1.3.1.	Hkube won't delete the data (including its logs) of marked pipeline's execution

**Comment by maty21** [comment]
dupi Job search API  #1446
