### ISSUE TITLE
Debug algorithm logs in UI

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1341]
Show logs written by algorithm locally debugged, in UI.

When running debugged algorithm i.e , pipeline runs in kubernetes environment, and algorithm runs on developers local machine, we want any out put the wrapper and algorithm prints to std out, to be transferred to the kubernetes environment , saved in elastic and shown in UI.

**Comment by tamir321** [comment]
the logs are received in the worker without jobIb and Task Id
"1645621321014, 2022-02-23T13:02:01Z, info, null, null, Algorunner, I was Here \n"
"1645621321014, 2022-02-23T13:02:01Z, info, null, null, Algorunner, I was Here 2\n"
"1645621321014, 2022-02-23T13:02:01Z, info, null, null, Algorunner, I was Here 3\n"
"1645621321014, 2022-02-23T13:02:01Z, info, null, null, Algorunner, I was Here 4\n"
