### ISSUE TITLE
improve logs of pipeline/algorithm execution

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#1359]
**Is your feature request related to a problem? Please describe.**
Some pipeline/algorithm execution flows are not traceable in the logs

**Describe the solution you'd like**
Need to add more logs

- [x] algorithm-queue - log jobId and taskId for each arrived job
- [x] pipeline-driver - log jobId for all logs. better logs for when sending redis jobs
- [x] worker - log code api with jobId and calling taskId and new taskId

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.4.2",
fullSystemVersion: "v2.4.2-1649763374965",
