### ISSUE TITLE
Handle algorithm deletion

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#138]
- [x] check all running pipelines, executions and triggers
- [ ] delete all jobs with this algorithm type from bull
- [ ] delete /algorithmRequirements
- [ ] delete /algorithmQueue

## UPDATE:
the decided solution was to tell the user that he needs to delete the follows, instead of deleting it and causing undesirable issues

### example for output 

```json
{
    "error": {
        "code": 400,
        "message": "algorithm green-alg is stored in 10 different pipelines, algorithm green-alg is running in 1 different executions, before you delete algorithm green-alg you must first delete all related pipelines and executions",
        "details": {
            "pipelines": [
                "simple-wait-batch",
                "trigger4",
                "trigger1",
                "batch",
                "simple",
                "big-batch",
                "trigger2",
                "big-wait-batch",
                "trigger3",
                "batch-on-node"
            ],
            "executions": [
                "raw-stress-c1aec3b788:1f9b52af-8f39-4fe6-9332-acaaa38fb246.raw-stress-c1aec3b788"
            ]
        }
    }
}
```

**Comment by Ronenk5678** [comment]
releated to #164

**Comment by NassiHarel** [comment]
* check all running pipelines and triggers - there is no need to check triggers.
For now, we are just validating if the algorithm exists in running pipelines and stored pipelines

**Comment by eytangro** [comment]
TID-530
