### ISSUE TITLE
possible inconsistency upon algorithm queue crashes 

### ISSUE THREAD

**Issue by maty21** [kube-HPC/hkube#1382]
### crash between backups could lead to this inconsistency 

related to issue #1377 

#### An incoming task that received but has not been back up yet:

In these case, we need to add a new state  under the taskId object on the ETCD for algorithm queue backup
the pipeline driver should listen to this state and verify that  the state changed correctly after timeout reached and if not to cancel the job

#### An outgoing job where the job was already sent but it still appears on the algorithm queue after the recovering 

In this case, the worker that gets the job should verify that the taskId state is correct

**Comment by NassiHarel** [comment]
## Solution:
1) Developed a snapshot module for backup data (NFS/S3) with no size limit.
2) Handle graceful shutdown, which will ensure that no new jobs will be processed and snapshot data before exit.
3) Limit the scoring array to max 5000, to avoid etcd errors.
