### ISSUE TITLE
Support  logging with a sidecar

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#1391]
**Is your feature request related to a problem? Please describe.**
When it is impossible to install fluentd as a daemonset, hkube needs to support logging with a sidecar of the logging agent
**Describe the solution you'd like**

- [x] Add support in [logger](https://github.com/kube-HPC/logger.hkube) for writing to file (see https://github.com/kube-HPC/hkube/issues/1390)
- [x] helm - add a sidecar of fluent-bit to all hkube workloads
- [x] helm - add configMap for fluent-bit
- [x] helm - add log file location env
- [x] hkube services - integrate new logger with config from env
- [x] task-executor - add sidecar to worker jobs
- [x] algorithm-operator - add sidecar to all deployments and jobs

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.1.88",
fullSystemVersion: "v2.1.88-1631616917808",
