### ISSUE TITLE
logs are taken very long to be written to ES

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#14]

**Comment by NassiHarel** [comment]
Also some logs are written many times to elastic 

![screenshot from 2018-02-11 17-48-49](https://user-images.githubusercontent.com/9460060/36075190-db37701c-0f53-11e8-8854-025ffba3a41f.png)

**Comment by eytangro** [comment]
it looks like the api server is not writing logs any more, i cant see the api server logs either in elastic and not in Kibana.

i don't know which other services stopped writing their logs

**Comment by NassiHarel** [comment]
Looks like fluentd issue
