### ISSUE TITLE
from time to time the node logs  are not refreshed when changing from node to node 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1400]
**HKube micro-service**
HKUBE WEB

**Describe the bug**
from time to time the node logs are not refreshed when changing from node to node 

**To Reproduce**
execute "simple" pipeline
open the job
select the different nodes and validate that the displayed log is the relevant log for the selected node
from time to time the log does not refresh and remain the log of the previous selected node

**Comment by maty21** [comment]
@tamir321  try to reproduce
