### ISSUE TITLE
Etcd periodic cleaner

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#142]

**Comment by NassiHarel** [comment]
need to use lease for deleting etcd data esily when job ended

**Comment by eytangro** [comment]
i ran a pipeline and after the pipeline completion i looked at the etcd and i saw the job in job results and in job status.

looks like the etcd cleaner dosent really work as needed

**Comment by bahalool** [comment]
pipeline clieaner should clean status and results
