### ISSUE TITLE
Recover from Redis disconnection

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1433]
while working on a pipeline the Redis disconnected 
the pipeline driver fail to report that the pipeline was completed and did not receive a new job

TODO: (also for master)
- [ ] health check interval (Api-Server)
- [ ] concurrency interval in (PDQ)
- [ ] race condition in concurrency (Api-Server)
- [ ] distinguish between applicative and IO errors

update(22.12)
Recovery scenarios

### 2.2
-  [ ] fix cunccrency functionality for pipeline driver queue from redis disconnection @yehiyam 
-  [ ] graceful exit when redis disconnects 
   -  [x] pipeline-driver
   -  [ ] pipeline-driver-queue
   -  [x] algorithm queue
    API server - No need for special handling, not in 1.3
   -  [x] worker - Not handled in 1.3
-  [ ] pipeline-driver: fail writing status/result/graph to MongoDB @golanha 
-  [ ] test MongoDB pod fail

### 1.3 
-  [x] add new path to etcd  
-  [x] on pipeline-driver update to active when getting the job 
-  [x] remove from etcd on done 
-  [x] sync on failures  
-  [x] pipeline-driver-queue get the data from the new path on uptime 
-  [ ] API for active jobs 
-  [ ]  add one way for gracfull shutdown on pipeline driver failuers
- [ ] pipeline-driver error in logs setJobStatus failed with error: A conflict occurred executing the software transaction (occurred once on prod )
- [x] pipeline-driver recovery:
-  the pd crashes for some reason (unknown at this point).
- Another pd gets the job
- starts recovery and starts working. Eventually (in this example it was after 70 minutes) crashes with error Unhandled rejection: unable to find task
-  pipeline-driver recovery: after pd is recovered 3 times, the bull job is not handled by the pdq and the jobs remains active

### etcd

- [x] pipeline-driver send job done even if cannot write result to etcd
- [x]  algorithm-queue fails to send job retry (worker stalled) if cannot write to etcd
- [x] #1496
redis
- [x]  pipeline-driver: graceful exit when Redis disconnects
misc
### testing: (@tamir321 )

- [ ]  stop etcd when worker is active
- [ ]  stop redis when worker is active
- [ ]  stop redis before sending pipeline
- [ ]  check trigger service on failures 
- [ ]  check concurrency on different scenarios   
- [ ]  check that there are available resources for creating new pipelines in case that there are no available resources on the cluster
- [ ]  test NFS failures  
- [ ]  check that when the API Server does not mark pipelines as max exceeded because of high rate of execution

**Comment by yehiyam** [comment]
Recovery scenarios
etcd
1. pipeline-driver send job done even if cannot write result to etcd
2. algorithm-queue fails to send job retry (worker stalled) if cannot write to etcd
 
redis
1. pipeline-driver: graceful exit when redis disconnects

testing:
1. stop etcd when worker is active
2. stop redis when worker is active
3. stop redis before sending pipeline

@tamir321 need to try and reproduce redis disconnect from network

**Comment by yehiyam** [comment]
More issues:
- [ ] pipeline-driver error in logs `setJobStatus failed with error: A conflict occurred executing the software transaction`
- [ ] pipeline-driver recovery:
- the pd crashes for some reason (unknown at this point). 
- Another pd gets the job
- starts recovery and starts working. Eventually (in this example it was after 70 minutes) crashes with error `Unhandled rejection: unable to find task`
- [ ] pipeline-driver recovery: after pd is recovered 3 times, the bull job is not handled by the pdq and the jobs remains active
