### ISSUE TITLE
Create output kind 

### ISSUE THREAD

**Issue by maty21** [kube-HPC/hkube#1448]
**Is your feature request related to a problem? Please describe.**

We need to create a new kind that collects results from other nodes and stores them as one object 

**Describe the solution you'd like**
In order to support this feature, we should  implement the follows:

- [x] Create a new kind that collects other node output as its input
- [x] Add it to Hkube's API
- [x]  Support this new kind on the Algorithm wizard on Hkube's dashboard

**Comment by maty21** [comment]
#1423

**Comment by tamir321** [comment]
tested on
systemVersion: "v2.2.40",
fullSystemVersion: "v2.2.40-1644834418052",
