### ISSUE TITLE
User ordering for pending jobs  - pipeline-driver-queue

### ISSUE THREAD

**Issue by maty21** [kube-HPC/hkube#1449]
**Is your feature request related to a problem? Please describe.**

We would like to add the ability for changing job's orders for jobs that have not started yet, this feature will add the flexibility needed in case Hkube's priority suggestion is not consistent with the user need's 

This feature should support the follows : 
 - [ ] Change the execution order for  a specific job or a group of jobs that their execution hasn't started
 - [ ]  Jobs that their execution order was set by the user, will be executed before all other jobs. 
 - [ ] _Optional:_ Hkube shall be enabled to operate all the above-mentioned capabilities using HKube's dashboard (@zivglik )

**Describe the solution you'd like**
Exposed API:
```
post
preferedjob/
jobs: [job1,job2]
adds a set of jobs as last among the prioritized jobs

preferredjob?before=otherJobid
jobs: [job1,job2]
adds a set of jobs to preferred, right after another job. If that job does not exist, add before all  preferred jobs

preferredjob?before=0
jobs: [job1,job2]
adds a set of jobs  before all  preferred jobs

get
preferredjob/
get list of preferred jobs according to their execution order

delete
preferredjob/
jobs: [job1,job2]
remove a set of jobs from preferred jobs

```

![Ordered pipeline driverqueue](https://user-images.githubusercontent.com/33115716/143816810-490cfe28-a3c3-41f4-a433-2ca9c443e8be.jpg)

- [ ] Create a new queue in the pipeline-driver queue this  queue will be cleaned before the existing one
- [ ]  for this queue we should add a cursor that references the job placed on the queue 
- [ ]  create a new API  that adds the ability to send  an array of jobs after the current cursor 
- [ ]  the first place on the queue will be ``cursor: null`` or ``cursor: -1``
- [ ]  _optional_:  creating maybe a new tab that shows the current queued job with the ability to aggregate them by a specific query  (@zivglik )
- [ ]  _optional_:   drag and drop those groups will change their order   (@zivglik )

**Comment by tamir321** [comment]
tested on
systemVersion: "v2.3.18",
fullSystemVersion: "v2.3.18-1648462268639",
