### ISSUE TITLE
UI: when the Datasource is disable It should be removed from the UI

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1473]
**HKube micro-service**
Dashboard

**Describe the bug**
UI: when the Datasource is disabled It should be removed from the UI
currently, it display error: "Failed fetching dataSources collection"

to disable DS set the:
datasources_service:
  enabled: false
in the HELM value file

**Comment by golanha** [comment]
Helm is missing configuration of simulator deployment

**Comment by golanha** [comment]
The environment variable: DATA_SOURCE_IS_ENABLE false value  reaches simulator, but still datasource not removed from UI
