### ISSUE TITLE
debug: debugged algorithm error is not reported

### ISSUE THREAD

**Issue by maty21** [kube-HPC/hkube#1474]
**HKube micro-service**
`node-wrapper`

**Describe the bug**
my code fails on error the Algorunner catches it and sends the error via WebSocket but for some reason, it does not fail the job.

**Expected behavior**
fail the job 

**To Reproduce**
1. run code with debugging on node.js with something that fails on runtime
2. run debug from the dashboard
3. the job is still active

**Additional context**
node wrapper version 2.0.50

**Comment by yehiyam** [comment]
There is no handling of `errorMessage` message in the debug worker.

**Comment by tamir321** [comment]
tested on
systemVersion: "v2.3.18",
fullSystemVersion: "v2.3.18-1648462268639",
