### ISSUE TITLE
Add active dashboard

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#1512]
**Is your feature request related to a problem? Please describe.**
It is not possible to see in the current number of active pipelines in grafana 
**Describe the solution you'd like**

- [x] Add pipeline_started and pipeline_ended metrics to pipeline-driver - see [release 1.3](https://github.com/kube-HPC/hkube/blob/c5505d08126f2d5591a400da19908756292d635e/core/pipeline-driver/lib/metrics/pipeline-metrics.js#L30) 
- [x] Add Active dashboard to helm chart - see [release 1.3](https://github.com/kube-HPC/helm/blob/release_v1_3/hkube/dashboards/HKube-Active.json)

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.3.6",
fullSystemVersion: "v2.3.6-1646752236311",
