### ISSUE TITLE
building algorithm - an algorithm version was not created after a successful build

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#1555]
**HKube micro-service**
API server
**Describe the bug**
building algorithm - an algorithm version was not created after a successful build 

**Expected behavior**

**To Reproduce**
build a new algorithm from code 
an algorithm version that includes the "Image path"  should be created 
the algorithm does not have  "Image path"  

**Additional context**

**Comment by yehiyam** [comment]
It looks like the watch for build changed events on the api server is not fired

**Comment by tamir321** [comment]
tested on 
systemVersion: "v2.3.18",
fullSystemVersion: "v2.3.18-1648462268639",
