### ISSUE TITLE
Dependent P.L request

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#157]
As a Pipeline Runner I want that Hkube will enable to activate pipeline automatically after the completion of other pipeline, in order to support modular workflow processing.
E.g. P.L B will be activated after P.L A, however P.L B can be activated directly by the user. using this capability the user doesn't need to duplicate P.L B definition (Part of P.L A and standalone)

**User story implementation details:**
1. Hkube shall enable the user to define dependent P.L descriptor, which will be automatically activated after successful activation of other P.L descriptor (one or more).
2. Hkube shall enable the user to update the dependent activation settings of P.L descriptor
3. Hkube shall enable the user to delete the dependent activation of P.L descriptor
4. HKube shall enable the user to subscribe/ unsubscribe to the result of the dependent activation of P.L descriptor. 
5. HKube shall enable the user to subscribe/ unsubscribe to the execution status of the dependent activation of P.L descriptor

**Comment by eytangro** [comment]
TID-450

**Comment by tamir321** [comment]
# cron Test

File: tid_400.js
describe : "TID-400 ~"

Test | description 
------|----------------
TID-430- cron jobs (git 154 155)~ | execute cron job
