### ISSUE TITLE
Dependent P.L request - Pipeline's result message

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#158]
As a Pipeline Runner I want that pipeline's result message for dependent P.L request will include the results of predecessor pipelines in order that I'll be able understand/ analyze the chain of activation.

**User story implementation details:**
1. The message will include the following:
1.1 Hierachy results of the predecessor pipelines in the activation chain of the dependent pipeline.
1.2 Result of the dependent pipeline
2. The data of the result for each of the above mentioned pipelines is described in #51

**Comment by eytangro** [comment]
TID-450

**Comment by eytangro** [comment]
what is the api endpoint for this?
is it even implemented?
