### ISSUE TITLE
Fetch dependent P.L descriptors

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#159]
As HKube manager I want to be able to fetch all the dependent pipeline descriptors which exists in the pipeline's Repository, so I can know which pipeline descriptors are configured as dependent.

**Comment by NassiHarel** [comment]
Done
use hkube/api-server/api/v1/pipelines/triggers/ to test

**Comment by tamir321** [comment]
#pipeline tree test

File:pipeline_tests.js 
describe : "Trigger pipeline"

Test | description 
------|----------------
Trigger tree | validate /pipelines/triggers/tree Get pipelines triggers
Trigger get result tree | validate /exec/tree/{jobId} Get pipeline execution tree 
Trigger cycle pipeline tree |  validate /pipelines/triggers/tree can handle cycle
