### ISSUE TITLE
Hkube runs more than a single instance of a service (sporadic issue)

### ISSUE THREAD

**Issue by ism55ism55** [kube-HPC/hkube#1651]
**HKube micro-service**
Algo service 

**Describe the bug**
1. Upon running a new job (no other jobs running in background && system is @ idle) hkube will run 2-3 instances of a algo service (sporadic). 
2. Another scenario: make sure that a single instance of a specific service is running at job start --> cause the service to crash -->  hkube will re-run the algo however it will run 2 (or even more) instances of this algo service although system is idle - sporadic

**Expected behavior**
A single instance of this service will run upon job start / service restart

**To Reproduce**
read above 2 scenarios

**Screenshots**

**Additional context**

**Comment by golanha** [comment]
Its a matter of configuration of hkube.
We need to set a value to an environment variable of hkube's task-manager deployment: 
CREATED_JOBS_TTL with a large value,  I checked , 45000 was sufisient.
