### ISSUE TITLE
problem  in update algorithm nodeSelector 

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1660]
Currently test "update algorithm nodeSelector " fails,  either the test or the functionality needs fixing

**Comment by lepilmen** [comment]
After re-writing the test, it seems that the first hotWorker doesn't go down && the new one doesn't go up.

**Comment by RonShvarz** [comment]
![image](https://user-images.githubusercontent.com/34660076/226925413-d9cf5063-b58e-43b0-a044-7fe66d93d857.png)

**Comment by RonShvarz** [comment]
Stable for more than 5 runs in a row, with the recent timeout change.
To be revised when logging flow is done.

**Comment by RonShvarz** [comment]
Swapped instance types in aws to have more CPU, rather than gpu nodes.
