### ISSUE TITLE
max retry on failing pods should return an error and close pipeline  

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#17]
if i fail the pod running a job over and over again, when it reaches a maximum retry count, it should return some kind of error either in the status update or result.

pipeline driver should be notified of this and act accordingly
as for now, no error is returned and the system still shows like it working on this job while no new pod is being raised

**Comment by NassiHarel** [comment]
For now only implemented in the pipeline-driver.
If the pipeline-driver pod is down and up, the pipeline should succeed or failed.

**Comment by eytangro** [comment]
i see that the details is showing 1 stalled, but the status remain active.
in this case i think its better to show failed status or something else, not active because the pipeline is no longer active
