### ISSUE TITLE
ui - add pipeline

### ISSUE THREAD

**Issue by zivglik** [kube-HPC/hkube#1704]
- [] Instead of @,#@,empty, write the functional name : 
 

|  @ | #@  |   |#   | 
|---|---|---|---|
| (@)Output of | (#@)Multi output of' | Value |  (#) Multi value
|  Example: < PrevNodeName >.attribute1. The output of other node |  Example:< PrevNodeName >.attribute1.  Each entry of previous node output array, will processed separately  |Example:   {"key": "value"} Or [1,"2",true] | Example: [1,2,3,4,] Each entry in given array will be processed separately.
| Validate that the value from the @ to the first dot or the end is a node name in the pipeline| Validate that the value from the @ to the first dot or the end is a node name in the pipeline.| Validate its a valid json | Validate its an array

  
- [x] Node input in case value is selected, should not be added as string.

**Comment by golanha** [comment]
Please change the example from @<NodeName>.attribute1  to @<NodeName> Or @<NodeName>.attribute1
