### ISSUE TITLE
Stateless block , Algorunner init/start method 

### ISSUE THREAD

**Issue by lersam** [kube-HPC/hkube#1726]
**HKube micro-service**
To which micro-service the bug related to, `Algorunner`.

**Describe the bug**
statles module , with three functions: **init, start, stop** 
as i understood init called before start. i made object initialization on 'init' and made module function call.
i received exception that module is undefined

**Expected behavior**
after call object on `init`, it should be live in `start`

**To Reproduce**
```
from hkube_python_wrapper import Algorunner


class Handler:
    def __init__(self):
        pass

    def on_input(self, msg):
        print(msg)


global my_handler:Handler = None


def init(args):
    global my_handler
    my_handler = Handler()

def start(args, hkube_api):
    global my_handler
    stream = args.get('streamInput')
    my_handler.on_input(stream.get('message'))


if __name__ == '__main__':
    Algorunner.Run(start=start, init=init)

```
**Screenshots**

**Additional context**

**Comment by golanha** [comment]
Change:
global my_handler:Handler = None
to 
global my_handler
my_handler = None

And will work
