### ISSUE TITLE
Error of event listener max exeeded  in algorithm-operator

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1737]
algorithm-operator restarts showing the events in pods log.
Apparently some limit is exeeded, throwing the folowing error: 
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit

Need to undrerstand where we register to an event in the event emiter and either unregister or avoid reregistering

**Comment by Adir111** [comment]
Clarification:
algorithm operator isn't restarting. This happens on any start-up of the pod.
Detailed explanation in PR.
