### ISSUE TITLE
Logs problem in debug algorithm in privleged false mode.

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1751]
Problem in task executer in creation of debug algorithm when system is ran in none priveleged mode.

The logs are not written as they do in a regular algorithm. 

To reproduce , install hkube with value false in isPriveleged configuration and run an algorithm in debug.

See image below.

![image](https://github.com/kube-HPC/hkube/assets/33115716/1bf07f69-b4f3-4200-8c23-3c5c126c4b78)

**Comment by RonShvarz** [comment]
Awaiting confirmation from users.
