### ISSUE TITLE
Allow to define maximum number of algorithm pods or streaming statless node and minimum in a streaming stateless node.

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1765]
In streaming we'd to allow a user to define number of statells pod instances that will start when the pipeline starts and belong to the job from the start ie  minimum stateless pods. We'd also like to be able to limit the nuber of instances of an algorithm in a specifc node.

**Comment by RonShvarz** [comment]
Opened a seperate issue for batch,
#1780
