### ISSUE TITLE
copy paste of algorithm json through ui, fails to create a new algorithm with diffrent name.

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1768]
Take an exsiting algorithm, copy it. Create a new algorithm move to json view, paste the algorithm json, rename the algorihm to a new name and try to submit the new algorithm. 
Acual: you will fail on missing file or some other run time error.

If submit of algorithm is done through the json editor view, skip any validations.

**Comment by zivglik** [comment]
After you copy old JSON after then
Investigate if there is a change from code to image
Why is there no version?

**Comment by zivglik** [comment]
There is no uploaded algorithm code file, but there is an algorithm docker image. Please change the type from code to image.

**Comment by zivglik** [comment]
QA UI
https://dev1.hkube.io/hkube/dashboard-cancel-msg-file-is-image/#/jobs?&experiment=main

**Comment by zivglik** [comment]
CODEREVIEW
https://github.com/kube-HPC/hkube/pull/1784
