### ISSUE TITLE
Add stateless count properties to UI json form

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#1791]
**Is your feature request related to a problem? Please describe.**
Following kube-HPC/hkube#1765 , minStatelessCount and maxStatelessCount are fields that are available for stateless nodes.
They need to be shown in the pipeline wizard in the text editor.

**Describe the solution you'd like**
Fields shown if they were added to a pipeline and exist in the database

**Additional context**
They are already added to the job-schema in api-server
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc05ZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--34ef55148490f8bd47360ae19a918d4ee63d52b6/image.png)

**Comment by zivglik** [comment]
need put  this after State Type 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVJsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3a91372ee41495526d6ef0a46543396f21373553/image.png)

**Comment by golanha** [comment]
In case values are set for the stateless count, we'd like to have the count pane expended.
