### ISSUE TITLE
import export of algorithms, pipelines.

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1794]
We'd like to support migrating data from a development environment to production environment.
All the data will be exported to a format that will later allow importing. 
Import and export will  be invoked via CLI invoking a rest API.
Old algorithm versions do not have to exported and imported.
We need to support different docker artifactory paths between environment.\

Exmple:
 _hkubectl export all -o /myDir_
 The export  all will build the following directory structure 
```
myDir
	pipenlines
		pipelines_1.json
	algorithms
		algorithms_1.json
```

The import all , will expect the same structure

 _hkubectl import all -i /myDir_

The following commandline command will aslo be supported:

 _hkubectl export algorithms -o /myDir/algorithms
 hkubectl import pipelines -i /myDir/pipelines_

Import command will allow to replace content with in the imported json/yaml.
hkubectl import algorithms -i /myAlgs -r docker.io=>myInternalRegistry

Acceptance creteria:
The user will get feedback as to what had been imported and what failed.
In case the import/export directory does not exist the user will be prompted with a clear message alerting.
If using the -r replace flag the user will be prompted on how many accourances had been replaced.

**Comment by mkkCoder** [comment]
hkubectl export all -o /myDir -f json/yaml
