### ISSUE TITLE
In "algorithms" section, notify for unfulfilled hot workers

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#1811]
**Is your feature request related to a problem? Please describe.**
When a request for X hot workers is not fulfilled ( there are less than X hot workers up for that specific algorithm ), note that it's an issue.

**Describe the solution you'd like**
Add info that states that there might be an issue

**Describe alternatives you've considered**
Adding a variable to later address in the UI

**Additional context**
For example, algorithms that were meant to run at a certain nodeSelector, that is there no more, and are forever in limbo.

**Comment by Adir111** [comment]
A new field has been added to each algorithm to determine if it has all the necessary workers, for both hot workers and regular workers.

For the UI, the query that retrieves all the algorithm data should additionally request the value `isSatisfied`.
