### ISSUE TITLE
Missing ci for helm bump - simulator patch

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#1824]
**HKube micro-service**
simulator, helm
**Describe the bug**
No simulator version update in values.yaml in helm's corresponding release branch, as seen when working on hkube core release branch
**Expected behavior**
Update helm values file correctly for simulator
**To Reproduce**
1. commits made on simulator's  release branch 
2. verify no action/commits in the corresponding helm value

**Comment by golanha** [comment]
done in commit (no RP) https://github.com/kube-HPC/simulator/commit/46c7cd6c7d0024167bf2fc3dab5b0e3283d317c8
