### ISSUE TITLE
Fix elastic prefix for kibana log link

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#1826]
in simulator : concat the prefix correctly after fetching the environment variable 'ELASTICSEARCH_STRUCTURED_PREFIX'

in helm :
1- rename the variable to the convention used in other elasticsearch vars
2- make the 'ELASTICSEARCH_STRUCTURED_PREFIX' variable be available under simulator

**Comment by golanha** [comment]
https://github.com/kube-HPC/simulator/pull/335
