### ISSUE TITLE
stateful block stopped in the middle of streaming pipeline due to "ZMQListener poll timeout"

### ISSUE THREAD

**Issue by ism55ism55** [kube-HPC/hkube#1837]
Reported by Yael:

**HKube micro-service**
worker / wrapper
 
**Describe the bug**
while streaming data to a pipeline job, stateful block gets stopped after several "ZMQListener poll timeout" warnings from wrapper.
After stop block still gets msgs from bus (but cannot process them correctly) and pod does not exit.
 
**Expected behavior**
if gets "ZMQListener poll timeout" which leads to stop also exit
 
**To Reproduce**
streaming pipeline
stateful blocks
run data through pipeline

**Comment by golanha** [comment]
Happned due to intensive, up and down of stateless. Too many sockets are created.
A certain fix in wrapper created the problem, since wrapper 2.5 DEV10 wrapper, problem is fixed
