### ISSUE TITLE
swagger pause resume test failing

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#1867]
**HKube micro-service**
system-test-node

**Describe the bug**
test the POST exec/pause/{jobId} and exec/resume/{jobId} rest call - fails if pause and resume are called too fast
**Expected behavior**

**To Reproduce**
test the POST exec/pause/{jobId} and exec/resume/{jobId} rest call - just run the test
Reproduces via UI aswell

**Screenshots**

**Additional context**
might be related to stop function in pipeline-driver that is invoked when pipeline is paused

**Comment by golanha** [comment]
Not relevant
