### ISSUE TITLE
stateless pods count Inconsistency between hkube jobs display and  stateless pods reported at grafana 

### ISSUE THREAD

**Issue by ism55ism55** [kube-HPC/hkube#1873]
**HKube micro-service**
version 2.6.20, UI
 
**Describe the bug**
while grafana HKUBE streaming dashboard displays that 15 stateless pods were up at the same time, in jobs UI stateless displays only 5 pod names
 
**Expected behavior**
jobs UI stateless should display all pods during the job
 
**To Reproduce**
streaming pipeline
stateful and stateless blocks (including min stateless pods definition)
start a pipeline, stream data in the way that 15 stateless will be created, monitor via jobs dashboard

**Comment by golanha** [comment]
Pods that were scaled (Not the minimum stateless pods)  were removed once completed. Fixed for 2.7 Release.
