### ISSUE TITLE
ZMQListener.fetch Operation not supported from multiple services

### ISSUE THREAD

**Issue by ism55ism55** [kube-HPC/hkube#1902]
**HKube micro-service**
HKube 2.6.20 reported by multiple types of micro servers "Worker" pods

*Error*:
ZMQListener.fetch Operation not supported

**Describe the bug**
During a 10 min run of sanity test i received numberless reports of the following error:

**Expected behavior**

**To Reproduce**
1. Run "simple" sanity automated test.

**Screenshots**

**Comment by golanha** [comment]
"Operation not supported" is an OSError encountered during handling by algorithm code.
May happen when trying to perform file system operation where not allowed.
I enhanced the log message so that is will be clearer where the error arrised.
