### ISSUE TITLE
algorithm <ALGO-NAME> has disconnected while in ready state, reason: 1000.

### ISSUE THREAD

**Issue by ism55ism55** [kube-HPC/hkube#1903]
**HKube micro-service**
HKube 2.6.20 Worker pod  

**Describe the bug**
During a 10 min run of sanity test i received multiple reports of the following:

*Error:*
algorithm <ALGO-NAME> has disconnected while in ready state, reason: 1000.

**Expected behavior**

**To Reproduce**
1. Run "simple" sanity automated test.

**Screenshots**

**Comment by golanha** [comment]
This warning would apear if the algorithm container suddely disconnected, with out sending a failure indication to worker.
