### ISSUE TITLE
Add minikube nginx solution for our users

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#1919]
In some newer versions of Minikube, nginx controller doesn't support snippet annotations.
To fix that issue, we need to edit the cm :
kubectl  -n ingress-nginx edit cm ingress-nginx-controller
and add the following annotation in the data part :

...
apiVersion: v1
data:
  allow-snippet-annotations: "true"
  hsts: "false"
kind: ConfigMap
...

Figure out a way to support this out of the box

**Comment by Adir111** [comment]
Note:
When installing helm, use this command:
helm install hkube my-chart --set isMinikube=true
