### ISSUE TITLE
Failed scheduling blocks the logs for all tasks in batch/stateless

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1924]
In case a node with mulitple tasks(statless/statefull) has tasks in  FailedSchedualing status, and has error/warnings in node level.

When you select such node the default  selected tasks filter valuis should contain both Failed and Active if there are such. A Failed schedualing task should be selected. The error or the warning in the Logs tab should only appear if a FailedSchedualing task is selected. 
The error or waring should also be adde to the tasks json that is shown in the input output tab.

**Screenshots**

**Additional context**

**Comment by zivglik** [comment]
check statelessPipe pipeline in dev
