### ISSUE TITLE
algorithm that failed and threw an error stays up in the system and not getting cleaned/deleted 

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#193]

**Comment by maty21** [comment]
and take system  resources according to @eytangro

**Comment by bahalool** [comment]
clean-old-jobs should clean jobs also in error from kubernetes
cron job should execute every 10seconds instead 10min

**Comment by bahalool** [comment]
task-executor should resurrect  error jobs (those job are in the highest priority since there where already ran  )
