### ISSUE TITLE
Workers tab in UI missing data

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#1938]
/hkube/dashboard/workers#/workers

Info that doesn't arrive / is not supported / needed:
Ready count, Working count, Init count, Exit count, Hot Count

What arrives - Count for example, comes from Query>discovery>taskExecutor>actual>stats
Investigate the data that does arrive, map the missing data, and what is currently available out of the existing columns.

<img width="841" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a442024347e8fb54b0c428be211b35a1e0374344/image.png" alt="image.png" />

**Comment by Adir111** [comment]
Related fields for data fetching query:
```
    algorithmName
    count
    init
    ready
    working
    exit
    hot
```
