### ISSUE TITLE
Maximum CPU Capacity

### ISSUE THREAD

**Issue by Adir111** [kube-HPC/hkube#1966]
**Is your feature request related to a problem? Please describe.**
When I tried to use 10 CPUs for an algorithm, I received a pop-up error message saying: "maximum capacity exceeded CPU (3 nodes)." The error message is unclear, as it does not specify what the maximum capacity is.

**Describe the solution you'd like**
I suggest changing the error message to "Maximum CPU exceeded (maxCPU)," where maxCPU is the maximum allowed CPU.

**Additional context**
The error message appeared when I tried to set the CPU for an algorithm to more than 8, which is the maximum allowed.

**Comment by golanha** [comment]
Add spaces in message.
Instead of (node1:8,node2:8....
State:  (node1: 8, node2: 8,...
