### ISSUE TITLE
Scale up of stateless algorithms takes long time (1-2 minutes)

### ISSUE THREAD

**Issue by tald-1** [kube-HPC/hkube#1974]
**HKube micro-service**
General issue, relevant to all stateless algorithms

**Describe the bug**
Scale up of stateless algorithms takes long time (1-2 minutes)

**Expected behavior**
Scale up of stateless algorithms will take up to ~10 seconds (from the moment scale up is needed till the service is ready to receive messages)

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by golanha** [comment]
duplicate: https://github.com/kube-HPC/hkube/issues/2002
