### ISSUE TITLE
No indication for algorithm not found in the UI

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#1984]
when filtering by algorithm name, and typing any prefix, or full name of an unexisting algorithm, the screen stays on the "loading" placeholder animation, giving the feeling the search is ongoing.
<img width="1210" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDV1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--710db4a431df3db1489aecb09851b16cdd7dea4a/image.png" alt="image.png" />

**Comment by zivglik** [comment]
<img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd09qQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ae5663397d9bc8dac6b019465853693838019a1/image.png" alt="image.png" />
