### ISSUE TITLE
Streaming pipeline grafana link in UI

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#1997]
When running a streaming pipeline, have a button for the grafana dashboard related to that pipeline.

i.e.

https://cicd-test.hkube.org/grafana/d/pWF8HslVk/hkube-streaming-edges?orgId=1&refresh=5s&from=now-3h&to=now&var-Pipeline_Name=video&var-Job_ID=6a8or2iw0wpo

**Comment by zivglik** [comment]
<img width="841" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzZpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af8fa67ab21694f7cd5d5b20f0d69638a9ea6dcc/image.png" alt="image.png" />
