### ISSUE TITLE
Reorgenize streaming edge tool tip

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#1999]
Streaming edge tool tip content is not clear to user, needs to be reorgenized.

Node1 - > Node2
When messages are sent from Node1 to Node2

**< Node1Name > :**
reqRate: 5.66 -> Messages produce rate: 5.66 per sec
queueSize: 37 -> Messages in queue: 37
queueTimeMs: 6790.84 -> Time messages spent in queue: 6790 ms
avgQueueSize: 37 -> Avg number of messages in queue: 37
roundTripTimeMs: 49.85 -> Handle acknowledge revieved after: 49.85 ms
totalRequests: 56 -> Total sent: 56
totalResponses: 18 -> Total handle acknowledged: 18
totalDropped: 0 -> Dropped messages: 0

**< Node2Name>**
resRate -> Message process rate:4
(Should only appear in case Node2 is stateless)  currentSize: 1  -> Number of instances: 1 
(Should only appear in case Node2 is stateless)   requiered: 2 ->  Needed instances: 2
(Should only appear in case Node2 is stateless)   resRate: 2.17 -> Process rate: 2.17 Messages per second
processingTimeMs: 0.04 -> Message process time: 0.4 ms

durationsRate:  -> remve it
grossDurationsRate: 20.06 -> remove it
throughput: -> remove it
desiered -> remove it
status - > remove it

**Comment by zivglik** [comment]
<Node1Name> (Src)
Messages produce rate: 5.66 per sec
Messages in queue: 37
Time messages spent in queue: 6790 ms
Avg number of messages in queue: 37
Handle acknowledge received after: 49.85 ms
Total sent: 56
Total handle acknowledged: 18
Dropped messages: 0

<Node2Name> (Dst)
(Should only appear in case Node2 is stateless)  Number of instances: 1
(Should only appear in case Node2 is stateless)  Needed instances: 2
(Should only appear in case Node2 is stateless)  Process rate: 2.17 Messages per second
Message process time: 0.4 ms
