### ISSUE TITLE
workers dont get aborted when there is a requirement for another algorithm

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#201]
i ran 2 pipelines each has different algorithm.
when pipeline A finished running pipeline B continued running but workers of algorithm A didnt aborted and replaced with algorithm B workers. even though there was a requirement for algorithm B workers

**Comment by yehiyam** [comment]
@eytangro @tamir321 please check if this is still an issue

**Comment by tamir321** [comment]
tested on version 1.2.35
