### ISSUE TITLE
Task status whithin pipeline's node log (UI)

### ISSUE THREAD

**Issue by RonShvarz** [kube-HPC/hkube#2010]
As seen below, when inside a pipeline, on the "Logs" tab, there needs th be attached to the Tשדל ID  it's corresponding task status 

 <img width="418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzdqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--192d5e3df8a1535372d452257a2451dfa40aae9c/image.png" alt="image.png" />

In the example above, next to x997p2j6, present it's task status ( active? stopped? etc.. )

**Comment by zivglik** [comment]
try color border **id task** by status color
