### ISSUE TITLE
Have hkubectl be delivered along with HKUBE helm installation.

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#2019]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Adir111** [comment]
This issue has been separated into two missions:

- [ ] Add the files into the site itself (the docker image of the site) and then when using the download page of the Hkube CLI - download them. Make sure the URL of the download is URL dependent. In this steps, the files are the current version we have.
- [ ] Make the files to be updated via GitHub workflow, triggering every time the hkubectl repository is updated.
