### ISSUE TITLE
transition is invalid in current state

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#203]
Sometimes worker gets uncaughtException:
transition is invalid in current state transition: start from:results, current: results

it's happens when worker get stop after results state

![Error jobs.png](https://images.zenhubusercontent.com/5a954bfe4b5806bc2bc89070/f39946ee-678e-4ac3-a91d-359f6f131a29)

**Comment by NassiHarel** [comment]
Recover by simulate error in algorithm

**Comment by bahalool** [comment]
if worker received invalid state than:
1) stop algorithm
2) kill kubernetes job
3) kill process
** task-executor should run new instance of worker instead this one (not implemented yet)

**Comment by eytangro** [comment]
could not reproduce
