### ISSUE TITLE
 unable to find handler for job

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#204]
When command 'stopProcessing' sent from task-executor the worker crashed.
the worker got stopProcessing command before register to any job:
uncaughtException: unable to find handler for <JOB_TYPE>

![Error jobs.png](https://images.zenhubusercontent.com/5a954bfe4b5806bc2bc89070/0a2981b1-4b90-442e-8159-e35be64678c4)

**Comment by NassiHarel** [comment]
- [ ] Ignore Error jobs in task executor
- [ ] Remove Error jobs in jobs cleaner

**Comment by bahalool** [comment]
if worker failed due to invalid state for example task-executor should start new instance of worker+algo
