### ISSUE TITLE
failed to start pipeline if "input" was missing from pipeline descriptor

### ISSUE THREAD

**Issue by bahalool** [kube-HPC/hkube#216]

**Comment by bahalool** [comment]
fixed with bug #199

**Comment by bahalool** [comment]
start pipeline without input for algorithm

**Comment by eytangro** [comment]
running a stored pipeline that didnt had input
returns an error: Cannot read property '0' of undefined.



{
    "jobId":"addmult:8ab65ce1-3c50-4e7e-9e8e-7fca4b9f3669.addmult",
    "timestamp":"2018-08-08T07:12:27.015Z",
    "pipeline":"addmult",
    "status":"failed",
    "error":"Error: Cannot read property '0' of null",
    "timeTook":1.756
}
