### ISSUE TITLE
Check high availability of K8s masters

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#217]

**Comment by eytangro** [comment]
TID-211

**Comment by tamir321** [comment]
#high availability of  Test

File: tid_161.js
describe: "TID-161- High Availability for HKube infrastructure services"

all the tests in this file test the high availability

**Comment by tamir321** [comment]
# pipeline queue Test

File: tid_51.js
describe : "tid_51 run pipelines in a queue~ (git 54)"

Test | description 
------|----------------
should run the eval batch pipeline | execute pipeline and validate have at least 15 running pods
should run the primes pipeline | execute pipeline and validate have at least 5 running pods
