### ISSUE TITLE
reconciler should kill redundant pipeline-drivers if defined less than actual running drivers

### ISSUE THREAD

**Issue by bahalool** [kube-HPC/hkube#255]
steps:
1: set PIPELINE_DRIVERS_AMOUNT = 30 in task-executor (defualt)
2: check 30 drivers running in kubernets
3: set PIPELINE_DRIVERS_AMOUNT = 1 in task-executor (defualt)
4: restart task-executor
5: still 30 drivers running instead only 1

**Comment by yehiyam** [comment]
sendCommandToDriver in task-executor is not written correctly. it writes the stopCommand to the discovery.
Also, the pipeline driver does not listen to these commands, and doesn't exit
