### ISSUE TITLE
driver should report error if process failed due to memory usage more than 256MB

### ISSUE THREAD

**Issue by bahalool** [kube-HPC/hkube#256]
set in ETCD /pipelineDriverTemplates/pipeline-driver
{
    "name": "pipeline-driver",
    "image": "hkube/pipeline-driver",
    "cpu": 0.15,
    "mem": 256
}
run pipeline with result of 260MB  --> driver should report for error

**Comment by NassiHarel** [comment]
Driver cannot report error in this case, memory usage is OS level....
