### ISSUE TITLE
simulator upgrade

### ISSUE THREAD

**Issue by maty21** [kube-HPC/hkube#264]
- [x]  fix errors 
- [x]  workers circles indicator 
#### stored pipeline upgrade : 
- [x] add cron switch button for enable/disable cron and integrate with  the api server
- [x] add cron view with the current cron setting (find good editor)
- [x] show 10 results status (blue,green, dark orange, orange) according to the jobs color convention
- [x] add an option to edit, delete pipeline
#### other
- [x] code refactoring 

#### Jobs
- [x] add button for download pipeline result
- [x] add input/output for each pipeline node

#### Algorithms
- [x] add an option to edit algorithm
- [x] add an option to upload algorithm source code
- [x] add full details for an algorithm update

#### Builds
- [x] add  an option to manage an algorithm builds

#### Monitor Server
- [x] fix the communication with the API-SERVER
- [x] fix the  communication with the simulator client

**Comment by denvash** [comment]
# Code Refactoring
- [ ] add `eslint`
- [ ] delete thirdParty
- [ ] migrate to `style-components`

**Comment by denvash** [comment]
# Cron adding

## Side missions

[x] - Make play icon - local
[ ] - Add hover to play icon
[ ] - Fix tabs counters

## Cron
[ ] - Cron table
