### ISSUE TITLE
Define algorithms which will be executed in the beginning of the pipeline

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#27]
As a Pipeline Builder I want to be able to define which algorithms (one or many) will be executed in the beginning of the pipeline execution.

**Comment by Ronenk5678** [comment]
**Description:**
As a Pipeline Builder I want to be able to define which algorithms (one or many) will be executed in the beginning of the pipeline execution.

**Comment by eytangro** [comment]
TID-300

**Comment by eytangro** [comment]
`Created by TestQuality - Linked to TestQuality.com requirement R8. Do not remove or edit.` [R8](https://hkube.testquality.com/project/5993/testcase/136673/requirement/5692)
