### ISSUE TITLE
Define the predecessor algorithms for each algorithm in the pipeline

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#28]
As a Pipeline Builder I want to be able to define the predecessor algorithms for each algorithm in the pipeline.

**User Story details:**
Predecessor algorithms can be of single pipeline type or more.
Pipeline type can be also batch algorithm
Transition condition of predecessor batch algorithm is defined as completion of all the batch algorithms

**Comment by Ronenk5678** [comment]
As a Pipeline Builder I want to be able to define the predecessor algorithms for each algorithm in the pipeline.

**User Story details:**
1. Predecessor algorithms can be of single pipeline type or more.
1. Pipeline type can be also batch algorithm
2. Transition condition of predecessor batch algorithm is defined as completion of all the batch algorithms

**Comment by eytangro** [comment]
TID-11

**Comment by eytangro** [comment]
`Created by TestQuality - Linked to TestQuality.com requirement R9. Do not remove or edit.` [R9](https://hkube.testquality.com/project/5993/testcase/136673/requirement/5693)
