### ISSUE TITLE
Wait all transition condition of batch algorithms

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#29]
As a Pipeline Builder I want to be able to define wait all transition condition for batch algorithms.
----
**User Story implementation details:**
_Wait all transition condition means:_ successful execution of all the batch algorithms before starting the successor algorithm of the batch algorithms.

**Comment by Ronenk5678** [comment]
As a Pipeline Builder I want to be able to configure the transition condition of predecessor batch algorithms, so that HKube will be able to execute part of the successor algorithm calculation in parallel to the batch algorithms
**User Story details:**
1. The transition condition of predecessor batch algorithm will enable the following options: 
1.1 Completion of all the batch algorithms before starting the successor algorithm.
1.2 Completion of only one of the batch algorithms before starting the successor algorithm.
3 **In both of the options**, the successor algorithm won't be completed till the completion of all the algorithms in the batch.

**Comment by eytangro** [comment]
TID-12

**Comment by tamir321** [comment]
the test can be found in 
https://github.com/kube-HPC/hkube/issues/34
