### ISSUE TITLE
Batch size is determined by calculation of predecessor algorithm

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#31]
As a Pipeline Builder I want that the HKube will enable to define in run time the number of batch algorithm instances based on calculation of predecessor algorithm (e.g. splitting big file into few smaller files).

**Comment by eytangro** [comment]
TID-12

**Comment by tamir321** [comment]
the test can be found in 
https://github.com/kube-HPC/hkube/issues/34
