### ISSUE TITLE
pipelines page- show pipeline details

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#327]
go to pipelines page, click on the + (plus) sign near one of the pipelines.
it still open the description and json tabs 
get an error-"ENOENT: no such file or directory, open '/hkubedata/test-hkube-store/readme/pipeline/simple.json'"

![Screenshot from 2019-05-28 11-23-25.png](https://images.zenhubusercontent.com/5a96c7e54b5806bc2bc8cb89/56a17535-1f43-411c-a315-39b58ff445df)

**Comment by denvash** [comment]
Fixed on PR [#37](https://github.com/kube-HPC/simulator/pull/37)
