### ISSUE TITLE
jobs page - Unnecessary filter icon at the Pipeline status column

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#328]
in the titles row the Pipeline Status has a filter icon that filters the view by values from 1-5, it is unnecessary.

![Screenshot from 2019-05-28 11-27-32.png](https://images.zenhubusercontent.com/5a96c7e54b5806bc2bc8cb89/191949a7-5c18-4841-81b2-df3207453572)

**Comment by denvash** [comment]
Fixed to readable form. #310
