### ISSUE TITLE
filter the jobs table by some key then run "simple" pipeline- ui craches

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#329]
in the search field of the jobs page, filter the table by some word, "simple"
than go to pipelines page and run the simple pipeline (it only occurs with the simple pipeline, maybe becouse its last i dont sure)
after running the pipeline go back to the jobs page and the page craches

![pageCrashes.png](https://images.zenhubusercontent.com/5a96c7e54b5806bc2bc8cb89/f27e4bc1-2578-4293-a394-6276fd8c5160)

**Comment by denvash** [comment]
From the error, you hadn't a connection on trying to running a pipeline,
I couldn't reproduce the error.
