### ISSUE TITLE
the UI is very slow

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#333]
once the ui is up and all elements are shown.
the ui is responding very slowly.
for example: go to the pipelines page and try to change one of the pipelines to cron job true.
the time passed from clicking on it and until the ui respond takes very long time.
need to try and make it response faster.

**Comment by denvash** [comment]
Added loading indication on `cron` switch.
On turning cron is takes time to get a response from the server - it's not that the "UI is slow".

Except that the UI feels ok across the application.

Fixed in PR [#37](https://github.com/kube-HPC/simulator/pull/37)
