### ISSUE TITLE
workers page open pod details crashes the page

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#334]
go to the workers page (make sure there are workers running)
open the algorithm details using the + button.
under it you see the pods details, click on the + button near the pod name the page crashes

![workers.png](https://images.zenhubusercontent.com/5a96c7e54b5806bc2bc8cb89/93e0c146-0383-4710-a0a3-915a031730cc)

**Comment by denvash** [comment]
Fixed, #310
