### ISSUE TITLE
view pod logs form the workers tab

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#336]
open the workers tab and expand an algorithm, to see all workers, press on the "view logs"
dosent do anything![viewlogs.png](https://images.zenhubusercontent.com/5a96c7e54b5806bc2bc8cb89/dbef9301-3f97-454d-b060-86f385f884fe)

**Comment by denvash** [comment]
This feature yet not implemented, I removed the button for now. 

Fixed on PR [#37](https://github.com/kube-HPC/simulator/pull/37)
