### ISSUE TITLE
post request endpoints are not correct

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#337]
open the console. 
most post requests from the client to the url that conatrin the monitor-server are passed with two slashes (//)
for example:
POST https://10.32.10.11/hkube/monitor-server*//*store/algorithms/apply 400

look between the monitor server and the store

![monitorserver url.png](https://images.zenhubusercontent.com/5a96c7e54b5806bc2bc8cb89/d0b2fc88-56b4-4811-8aed-4d0bfdafcff5)

**Comment by denvash** [comment]
Fixed some versions before (`1.1.142`)
