### ISSUE TITLE
Enhance failed pipe line(Job) error information

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#339]
Enhance failed pipeline error information. The error information in the failed pipeline instance (-Job) result. , should be structured, allowing to determine failure reasons:
If pipeline exceeded TTL, error should have running time duration of each algorithm that ran, time wasted waiting for resources to start each algorithm.
If an algorithm through an exception, error should indicate which node and algorithm through the exception.

**Comment by amiryi365** [comment]
**This is important** because if you have a big pipeline (lots of nodes) it takes time to find the failed tasks, especially because of #657

**Comment by NassiHarel** [comment]
Fixed
