### ISSUE TITLE
Part or all of the inputs of algorithm are taken from the pipeline's request

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#34]

**Comment by eytangro** [comment]
TID-10

**Comment by eytangro** [comment]
`Created by TestQuality - Linked to TestQuality.com requirement R3. Do not remove or edit.` [R3](https://hkube.testquality.com/project/5993/testcase/136626/requirement/5687)

**Comment by eytangro** [comment]
`Created by TestQuality - Linked to TestQuality.com requirement R5. Do not remove or edit.` [R5](https://hkube.testquality.com/project/5993/testcase/136672/requirement/5689)

**Comment by eytangro** [comment]
`Created by TestQuality - Linked to TestQuality.com requirement R6. Do not remove or edit.` [R6](https://hkube.testquality.com/project/5993/testcase/136672/requirement/5690)

**Comment by tamir321** [comment]
#  Test

File: tid_10.js
describe : "TID-10 , Part or all of the inputs of algorithm are taken from the pipeline\'s request (git id -  34,32)"

Test | description 
------|----------------
should return result 24 | execute pipeline validates results
should return result 18 | execute pipeline validates results
should run the pipeline twice | execute pipeline twice

describe : "TID 11 - Define_the_Pipe_Line_order"

Test | description 
------|----------------
Define_the_Pipe_Line_order | execute pipeline algorithm order

describe : "TID 12 - determine batch size (git 29,30,31)"

Test | description 
------|----------------
Define_the_Pipeline_hirarchy | execute pipeline validate results
