### ISSUE TITLE
Allow defining TTL in Algorithm/Node level

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#342]

**Comment by yehiyam** [comment]
duplicate of #601

**Comment by tamir321** [comment]
#Algorithm TTL test
File: algorithm_tests.js
describe : "TID 480 - Test Algorithm ttl (git 61 342)"

Test | description 
------|----------------
ttl = 3 one of the inputs = 5 seconds | execute algorithm with ttl 3 seconds and duration 5 seconds
ttl =0 one of the inputs = 5 seconds | execute algorithm with ttl=0 ( no error )
