### ISSUE TITLE
python automated build ignores exceptions on ws.send

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#383]
**HKube micro-service**
python-wrapper.hkube

**Describe the bug**
When an exception occurs in `WebsocketClient.send` it is swallowed and not propagated to the wrapper to fail the algorithm
**Expected behavior**
The algorithm should fail

kube-HPC/python-wrapper.hkube#1

**Comment by NassiHarel** [comment]
https://github.com/kube-HPC/python-wrapper.hkube/commit/4d7d748323b5c8fecbf009889d3a9d39ad6fc2c9
