### ISSUE TITLE
python automated build - unable to serialize binary data

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#384]
**HKube micro-service**
python-wrapper.hkube

**Describe the bug**
If the algorithm returns binary data, the json library fails with the error   
`Object of type bytes is not JSON serializable`

**Comment by NassiHarel** [comment]
https://github.com/kube-HPC/python-wrapper.hkube/commit/4d7d748323b5c8fecbf009889d3a9d39ad6fc2c9

**Comment by tamir321** [comment]
old issue  solved by binary worker
tested with algorithm returning binary data
