### ISSUE TITLE
Allow user to specify different npm repository for builds

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#387]
should set repository during installation for on prem   hkube's installation

**Comment by eytangro** [comment]
TID-650

**Comment by tamir321** [comment]
test was added to algorithm build test

**Comment by tamir321** [comment]
# different npm repository  Test

File: algorithmBuild.js
describe : "Algorithm requirements repository (git 387)"

Test | description 
------|----------------
python with requirements - tensore |build pytjon algorithm with tensor board
nodejs with requirements - lodash| build node algorithm with lodash
