### ISSUE TITLE
input output details on a worker

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#401]
on the jobs page open a pipeline and press on one of the workers to see its logs,
in the log page there is a "input output details" tab. when pressing on it, the page crashes

**Comment by denvash** [comment]
On opening an issue, please use the bug template on
![image](https://user-images.githubusercontent.com/27515937/60393469-a5882d00-9b1e-11e9-8a02-03bdcecf634c.png)

**Comment by denvash** [comment]
Which version you using, I can't reproduce on `1.1.149v`

![image](https://user-images.githubusercontent.com/27515937/60393498-04e63d00-9b1f-11e9-87af-10fb05e26e05.png)
