### ISSUE TITLE
worker page pod additional details

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#402]
on the workers page, click on an algorithm so see its pods, expand a pod and click on he "Additional Details" tab. 
all data there is undefined

**Comment by denvash** [comment]
Please use the bug template 
![image](https://user-images.githubusercontent.com/27515937/60393469-a5882d00-9b1e-11e9-8a02-03bdcecf634c.png)

**Comment by denvash** [comment]
Fixed on [#44 PR](https://github.com/kube-HPC/simulator/pull/44) @ Dashboard
