### ISSUE TITLE
drivers page- sort

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#403]
in the driver page (and almost in every page),  try to sort the table by clicking on the table header,
the page crashes

**Comment by denvash** [comment]
On opening an issue, please use the bug template on
![image](https://user-images.githubusercontent.com/27515937/60393469-a5882d00-9b1e-11e9-8a02-03bdcecf634c.png)

**Comment by denvash** [comment]
Fixed on [#44 PR](https://github.com/kube-HPC/simulator/pull/44) @ Dashboard
