### ISSUE TITLE
edit description. both on pipelines and algorithms

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#404]
go to pipeline or algorithm and click on the description tab and press edit description.
the description window will open, try to edit it and while editing it press on the keyboard on one of the arrow keys, the edit window is automatically closing which makes it very hard to edit the data

**Comment by denvash** [comment]
Fixed on [#44 PR](https://github.com/kube-HPC/simulator/pull/44) @ Dashboard
