### ISSUE TITLE
pipeline description

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#405]
edit some pipeline description.
submit it and reload the page, open the pipeline description and you see what you wrote.
click on the edit button again to edit what you wrote before. the edit screen is once again the default template.
it needs to be the same as you saved it before

**Comment by denvash** [comment]
@eytangro can you use the template?

**Comment by denvash** [comment]
Fixed on [#44 PR](https://github.com/kube-HPC/simulator/pull/44) @ Dashboard
