### ISSUE TITLE
Pipeline request using pipeline which is stored in the repository of pipeline descriptors

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#41]
As a Pipeline Runner I want to be able to send a pipeline request for pipeline, which exists in the repository of the pipeline descriptors.
---
### User Story implementation details:
1. Basic Request parameters:
1.1. Pipeline descriptor name
1.2. Input parameters for the pipeline request
2.  Validity check: Upon reception of the request, HKube will verify that there exists a pipeline descriptor with the name in the request
2.1 If the validity check will fail, HKube will response with error and appropriate error description.
3. Otherwise
3.1 HKube will execute the request and respond to the pipeline request with the pipeline request Id (generated by HKube)
3.2 Hkube will write to the pipeline log, the event of receiving pipeline request with the following detailes:
3.2.1 General pipeline details, see REQ_73
3.2.2 Pipeline name
3.2.3 Event description - receiving pipeline request

**Comment by Ronenk5678** [comment]
As a Pipeline Runner I want to be able to send a pipeline request for pipeline, which exists in the pipeline's Repository.

User Story implementation details:
1. Basic Request parameters:
1.1. Pipeline descriptor name
1.2. Input parameters for the pipeline request
2. Validity check: Upon reception of the request, HKube will verify that there exists a pipeline descriptor with the name in the request
2. If the validity check will fail, HKube will response with error and appropriate error description.
3. Otherwise
3.1 HKube will execute the request and respond to the pipeline request with the pipeline request Id (generated by HKube)
3.2 Hkube will write to the pipeline log, the event of receiving pipeline request with the following detailes: 
3.2.1 General pipeline details, see REQ_73
3.2.2 Pipeline name
3.2.3 Event description - receiving pipeline request

**Comment by eytangro** [comment]
TID-320, TID-330, TID-340

**Comment by eytangro** [comment]
`Created by TestQuality - Linked to TestQuality.com requirement R4. Do not remove or edit.` [R4](https://hkube.testquality.com/project/5993/testcase/136626/requirement/5688)

**Comment by eytangro** [comment]
`Created by TestQuality - Linked to TestQuality.com requirement R7. Do not remove or edit.` [R7](https://hkube.testquality.com/project/5993/testcase/136672/requirement/5691)

**Comment by tamir321** [comment]
# Fetch all pipeline descriptorsTest

File: tid_310.js
describe : "pipeline actions"

Test | description 
------|----------------
TID-340- get all pipeline (git 70 41)  | validate  Fetch all pipeline
