### ISSUE TITLE
Cancel the execution of pipeline request

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#42]
As a Pipeline Runner/ HKube Manager I want to be able to cancel the execution of pipeline request by pipeline request ID. 

Relevant in the following scenarios:
- The request was sent with wrong parameters
- The request isn't relevant anymore - e.g. too much time passed since the request was sent or new data arrived.
- The request was sent by mistake
---
### User Story implementation details:
Upon receiving cancel pipeline request the following actions will be performed:
1. Validation checks:
1.1 Verify that the request ID in the request exists in HKube
1.2 Verify that the status of the pipeline isn't completed/ cancelled
2. If one (or more) of the validation checks fail, HKube will return failure with appropriate error message.
Otherwise:
3. The execution of all P.L's algorithms will be stopped/ deleted from queue.
4. Cancel action will be written to the log of the pipeline, including the following details:
4.1 General pipeline details, see REQ_73
4.2 Event description - Cancel pipeline. Reason of cancelling the P.L: user request
5. Pipeline's status will be updated to canceled and pipeline's status message will be sent to the user (detailed in REQ_62)

**Comment by eytangro** [comment]
TID-50

**Comment by tamir321** [comment]
# stop pipeline  Test

File: tid_50.js
describe : "stop pipeline while its runing"

Test | description 
------|----------------
should stop the pipeline while running (git 42) | stop pipeline
