### ISSUE TITLE
Pipeline request using pipeline which isn't stored in the repository of pipeline descriptors

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#43]
As a Pipeline Builder I want to be able to execute pipeline, which isn't stored in the repository of pipeline descriptors, so I can test pipeline before it is published (stored in the pipeline repository).
---
### User Story implementation details:
1. Basic Request parameters:
1.1. Pipeline descriptor file
1.2. Input parameters for the pipeline request
2. Validation check
2.1 Upon reception of the request, HKube will verify that all of the algorithms which are used in the pipeline descriptor are installed in the system.
2.2. If the validation checks will fail, HKube will response with error and appropriate error description.
3. Otherwise
3.1 HKube will execute the request and  respond to the pipeline request with the pipeline request Id (generated by HKube)
3.2 Hkube will write to the system log, the event of receiving pipeline request with the following detailes: 
3.2.1 General pipeline details, see #89
3.2.2 Event description - receiving pipeline request with pipeline descriptor file

**Comment by eytangro** [comment]
TID-310

**Comment by eytangro** [comment]
when running a raw request with a non existing algo , there is no assertion and the pipeline is started and being stuck.

{
	"name": "bigevaltest",
	"nodes": [
		{
			"nodeName": "evaladd",
			"algorithmName": "**someAlgo**",
			"input": [
				[
					"(input,require)=> {",
					"const result= input[0][0]+input[0][1]",
					"return result;}"
				],
				"@flowInput.addInput"
			]
		},
		{
			"nodeName": "evalmul",
			"algorithmName": "eval-alg",
			"input": [
				[
					"(input,require)=> {",
					"const result = input[0][0]*input[1]",
					"return result;}"
				],
				"@flowInput.multInput",
				"@evaladd"
			]
		}
	],
	 "flowInput":{
      "addInput":[3,5],
      "multInput":[3]
  }
 }
