### ISSUE TITLE
race condition in dashboard

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#430]
**HKube micro-service**
Dashboard

**Describe the bug**
the dashboard crashes.
a raise condition is raised, I had it when I was executing a lot of pipelines one after the other

**Expected behavior**
the dashboard to no crash  

**To Reproduce**
1. run a lot of pipelines one after the other
2. at some point the dashboard will crash

**Screenshots**
![Screen Shot 2019-07-22 at 10.55.29.png](https://images.zenhubusercontent.com/5a96c7e54b5806bc2bc8cb89/6dfc0a96-ba9b-40f0-8cc1-37dd7805c0b6)

**Additional context**

**Comment by denvash** [comment]
Fixed on performance PR @ Dashboard
