### ISSUE TITLE
node input output details doesn't show

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#441]
**HKube micro-service**
dashboard
**Describe the bug**
run a pipeline, after it started running go to one of the nodes input-output data, nothing shows
**Expected behavior**
it should show the data

**Additional context**
the data was removed due to large data that made monitor server fail of OOM

**Comment by denvash** [comment]
Fix on [#47](https://github.com/kube-HPC/simulator/pull/47) PR @ Dashboard
