### ISSUE TITLE
turning on a cron job for a pipeline

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#442]
**HKube micro-service**
dashboard
**Describe the bug**
when you try to set a cron job for a pipeline from the dashboard the UI fail and a white page is present

**Expected behavior**
should set a cron job for a pipeline

**To Reproduce**
1. go to pipelines page
2. pick a pipeline and click on the cron job radio button to activate it
3. the UI fials and white page appears
4. the cron job is not set, event the text area for the cron pattern isnt become active

**Comment by denvash** [comment]
Fixed on [#47](https://github.com/kube-HPC/simulator/pull/47) PR @ Dashboard
