### ISSUE TITLE
pipelines page

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#443]
**HKube micro-service**
dashboard

**Describe the bug**
the pipelines page crashes

**To Reproduce**
im not sure what happend it worked and than it stopped.
going to the pipelines page crashes the UI.
see errors in the screenshot
i tried refreshing the page several times and nothing halpes
**Screenshots**
![Screenshot from 2019-07-29 13-52-06.png](https://images.zenhubusercontent.com/5a96c7e54b5806bc2bc8cb89/ac3c5a01-1888-4f41-8dbf-b7970c58f95e)

**Comment by denvash** [comment]
#422 

Fixed on [#47](https://github.com/kube-HPC/simulator/pull/47) PR
