### ISSUE TITLE
cpu usage when adding an algorithm

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#444]
**HKube micro-service**
dashboard
**Describe the bug**
when adding an algorithm, with the wizard, the cpu usage text area  is only int
**Expected behavior**
cpu usage should be also not ints, i can deside to use 0.5 cpu for example
**To Reproduce**
1. go to "Add algorithm"
2. in the cpu usage area type "0.5"
3. unfocuse the text area the text entered changes back to 1

**Comment by denvash** [comment]
Can't reproduce, seems like there is no bug.
