### ISSUE TITLE
Stop algorithm build

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#452]
**HKube micro-service**
dashboard
**Describe the bug**
trying to stop an algorithm build fails

**To Reproduce**
1. build an algorithm, and while its building press on the stop button
2. the build isn't stopping and an error is shown

**Screenshots**
 ![Screenshot from 2019-08-01 10-27-03.png](https://images.zenhubusercontent.com/5a96c7e54b5806bc2bc8cb89/4aea9790-46c4-43a6-8f22-1d2a63a58b12)

**Additional context**

**Comment by denvash** [comment]
Bug not related to `Dashboard`, you hadn't connected to `API-Server` on that moment.
