### ISSUE TITLE
ui crashes if you click on a view before the data was loaded

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#460]
**HKube micro-service**
dashboard

**Expected behavior**
should work and not crush

**To Reproduce**
1. best to see it in test env, because there is a lot of data there
2. go to the simulator url
3. it takes a while to load every thing, while every thing is not loaded yet click on "workers"
4. the ui crashed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a96c7e54b5806bc2bc8cb89/9e5cf179-5be3-4f78-bdae-4983b433052f)

**Comment by denvash** [comment]
Fixed
