### ISSUE TITLE
download pipeline results dosent work

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#468]
**HKube micro-service**
dashboard
**Describe the bug**
download pipeline result dosent work
**Expected behavior**
shold work and download the results
**To Reproduce**
1. run pipeline
2. when it finished click on the "download results" button
3. dev tools show:
rest.middleware.js:44 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at ce (rest.middleware.js:44)
    at ae (rest.middleware.js:14)
    at rest.middleware.js:170

**Comment by denvash** [comment]
Can't reproduce.
