### ISSUE TITLE
dashboard crashes 

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#473]
**HKube micro-service**
dashboard
**Describe the bug**
The dashboard suddenly crashed

**Screenshots**
![image](https://user-images.githubusercontent.com/6139491/62722571-6dc2ae00-ba17-11e9-8923-f07f5613b742.png)

**Comment by denvash** [comment]
Happened due to `nodeStats` returned `{}` (object) on empty stats (should return `[]`).

Fixed.
