### ISSUE TITLE
Subscription (push interface) to pipeline result

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#48]
As a Pipeline Runner I want to be able to subscribe (push interface) to receive the result of the pipeline, so I wont need to pull the result of the pipeline.
---
### User story implementation details:
1. The subscription will be optional and will be done by passing result reception interface as parameter of the pipeline request.
2. Subscriber of pipeline's result will receive pipeline's result message (detailed in REQ_107) when the HKube will finish to write the pipeline's result.

**Comment by eytangro** [comment]
TID-112
