### ISSUE TITLE
we should verify that checksum operation for algorithm build is not heavy 

### ISSUE THREAD

**Issue by maty21** [kube-HPC/hkube#488]
**HKube micro-service**
API-Server.

**Describe the bug**
we should verify that the operation doesn't take to long
if so  we should thinking of moving the operation to other microservice or even remove it 

**Expected behavior**
the operation will not be heavy.

**To Reproduce**
1.  try to build with large tar.gz and with a lot of files within the tar.gz

**Comment by NassiHarel** [comment]
Checked: very light
