### ISSUE TITLE
Pipeline's status message

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#49]
As a Pipeline Runner I want that HKube will be able to send pipeline status message, so that I'll be able to view the progress of the pipeline during its execution.
---
### User story implementation details:
The message will include the following information:
1. The state of  the pipeline (see REQ_105)
2. Status of algorithms:
2.1 Quantity of algorithms per state (e.g. 5 Completed, 2 Handled)
2.2 Per algorithm the following information will be included:
2.2.1 Algorithm ID
2.2.2 Algorithm type
2.2.3 Progress indication in percentage - only for algorithms which support progress indication.

**Comment by eytangro** [comment]
TID-113
