### ISSUE TITLE
when running a cached pipeline no message showing the pipeline started to run

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#491]
**HKube micro-service**
dashboard
**Describe the bug**
when running a cached pipeline no message showing the pipeline started to run

**Expected behavior**
should show a message the the pipeline will start running 

**To Reproduce**
1. run some pipeline 
2. when it finished, run one of its nodes again in cache
3. the pipeline start running without a message on the dashbord

**Comment by denvash** [comment]
Fixed on PR [#57](https://github.com/kube-HPC/simulator/pull/57)
