### ISSUE TITLE
run cached pipeline from a batch

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#494]
**HKube micro-service**
caching service

**Describe the bug**
run a cached pipeline from a batch wont run

**Expected behavior**
should run

**To Reproduce**
1. run pipeline with batch
2. try to rerun the batch using the cache option 
3. a new pipeline starts to run but failing with an error: "Cannot read property 'result' of undefined

**Comment by NassiHarel** [comment]
Duplicate kube-HPC/hkube#781
