### ISSUE TITLE
Node Information of an algorithm that ran from code API

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#503]
**HKube micro-service**
dashboard
**Describe the bug**
there no logs for such an algorithms

**Expected behavior**
should behave the same as other algorithms

**To Reproduce**
1. run pipeline that the first algorithm calls another algorithm using the code API
2. when the pipeline ends click on the box of the algorithm that ran from the code API
3. there should be Node Information but nothing happens

**Comment by denvash** [comment]
Fixed on previous versions.
