### ISSUE TITLE
Build algorithm out of a git remote repository

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#505]
As a user I'd like to define a new algorithm similar to the way I would "Create Algorithm from code" today. Only instead of uploading a tar file with the code, I would point to a specific branch in a git remote repository.

Acceptance criteria:

- [ ] Content of a tar currently used for algorithm automatic build  should now work the same out of a git branch using rest.
- [ ] Support https git remote repository.
At this stage only working against repository that do not need authentication.

**Comment by eytangro** [comment]
TID-590
