### ISSUE TITLE
Automatic build from git supports Token authentication against git rep

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#507]
As a user I'd like to be able to build an algorithm from a git remote repository that needs authentication.

**Comment by tamir321** [comment]
# build algorithm test

File:algorithmBuild.js 
describe : "git hub and git lab algorithm builds (git 506)"

Test | description 
------|----------------
build github master algorithm | build algorithm from github
build gitlab master algorithm | build algorithm from gitlab

*** missing   token done manually
***  missing Token from git hub and git lab
