### ISSUE TITLE
Expose API for gitlab and github webhook upon push

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#518]
After adding an algorithm from code in git. A user will be able to set a webhook on gitlab or github, so that upon push to a branch if an algorithm was built out of this branch, the algorithm will be rebuilt.
A user will be able to enable or disable rebuilding of the algorithm upon webhook invocation.

**Comment by tamir321** [comment]
# git hub and lab Test

File: algorithmBuild .js
describe: "git hub and git lab algorithm builds (git 506)"

Test | description 
------|----------------
test webhook github (git 518)| test git lab web hook 
test webhook gitlab (git 518)|test webhook gitlab
