### ISSUE TITLE
Request for pipeline's result message

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#52]
As a Pipeline Runner I want to be able to send pipeline result request by pipeline request ID, so I'll be able to query the pipeline's result.
---
### User story implementation details:
1.Upon reception of pipeline result request, HKube will perform the following validation checks:
1.1 Verify that the request ID in the request exists in HKube. 
1.2 Verify that the status of the pipeline is Completed
2. If one of the validation checks will fail, HKube will reply with error code and relevant error description
3.Othewise, HKube will send pipeline's result message for the request ID (detailed in REQ_107)

**Comment by eytangro** [comment]
TID-113
