### ISSUE TITLE
Known UI Issues

### ISSUE THREAD

**Issue by denvash** [kube-HPC/hkube#525]
- [ ] missing pagination for batch algorithm: currently there is a limitation for 10 records of the batch input-output.
in the case of batch > 10, there is no way to view the details and debug.

- [ ] **Trace:** On long trace logs, `Jaeger Trace Component` trims the logs from a certain spot and displays an empty space. It causes a long empty page from a certain point. 
   - Possible fixes:
       1. Find a possible fix within the `Trace` component (3rd party component).
       2. Implement a custom trace component
       3. Show a reasonable amount of logs (1000+ log lines are not reasonable), redirected to Jaeger trace page on demand.

- [x] **Markdowns:** with the current implementation, on every markdown request, we saving its info in the UI state, it may cause memory/performance issues when a user fetches "many" markdowns.
   - Possible fixes:
       1. Refactor the markdown implementation, without abusing the state object.

- [x] **Performance**: with the current implementation, we re-render the `Job Table` on every socket fetch, the render time exponentially grows depending on the total jobs, it may cause UI thread to block the application use.
Average render time is **123ms** (After the memoization refactor which reduced the render time from **215ms**).
   - Possible fixes:
       1. Optimization to the buttle neck which is the `JobsTable` component- every job should be with a unique id for rendering indication.

- [x] **Production Bundle-Size**: Current size **8.06MB** and the main chunk (the first chunk delivered to the client) is **7.48MB**, causes a long build time and a warning (_not recommended bundle size_) on each build.
   - Possible fixes:
       1. Code-Splitting: 
            - Splitting `monaco-editor` reduced bundle to **6.18MB** and main chunk **4.63MB**
            - Splitting `vis-graph` reduced main chunk to **3.93MB**
            - Splitting `codemirror` which is dependency of `SimpleMDE` (markdown editor) and minor `lodash` functions reduced the main chunk to **3.64MB** which is recommended size.

After some tweaking, final result: bundle size **4.91MB** and main chunk **3.66MB**.
You can inspect the [prev source map](https://bw2cn.csb.app/) and the [final result](https://z15p0.csb.app/).

- [ ] **User Exp**
    - [x] When the user leaves webhook empty, no webhooks should be sent, e,g:

		``` 
		"webhooks": {
		    "progress": "http://",
		    "result": "http://"
		}
		```
    - [x] Add pause and resume implementation.
    - [ ] On edit pipeline/algorithm, open the wizard, not JSON.
    - [ ] Add option to download source code of algorithm.
    - [x] Add Default button for json editors.
    - [x] Versions - View the specific version details (JSON).
    - [ ] Update algorithm name will create a new algorithm (need to block on 
edit)
    - [ ] Add algorithm keep value on changing to editor view.
    - [ ] Job Card remains in card view.

- [ ] **README**
  - [ ] There is no option for adding README when on adding a new pipeline/algorithm.
- [ ] **Batch**
  - [ ] Need to fetch batch items by demand using the API /graph/<jobID>/parsed.
- [x] **Logs**
  - [x] Add option to select log provider (k8s, es)
  - [x] Add option to change logger's verbosity level

**Comment by NassiHarel** [comment]
- [ ] Enable restart stopped build

**Comment by maty21** [comment]
- [ ] remove status and results from JSON view
- [ ] change name from JSON to information 
- [ ] add overflow to logs

**Comment by denvash** [comment]
- [x] Run algorithm from entry row
