### ISSUE TITLE
Manage pipeline requests in a queue

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#54]
As a HKube Manager I want that Hkube will manage pipeline requests in a queue, so that requests won't be lost in case there isn't available HW resources.

**Comment by eytangro** [comment]
TID-51 in betta1 version doc

**Comment by tamir321** [comment]
# pipeline queue

File: tid_51.js
describe : "tid_51 run pipelines in a queue~ (git 54)"

Test | description 
------|----------------
should run the eval batch pipeline | execute  pipeline and validate result
should run the primes pipeline | execute  pipeline and validate result
