### ISSUE TITLE
Add Graph API & Improve the pipeline graph

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#545]

**Comment by tamir321** [comment]
graph api tests was added to swagger test

**Comment by tamir321** [comment]
# Graph  Test

File: swaggerCalles.js
describe : "graph api (git 545)"

Test | description 
------|----------------
Get /graph/raw/{jobId} and rest call | Get /graph/raw/{jobId} and rest call
Get /graph/parsed/{jobId} and rest call| Get /graph/parsed/{jobId} and rest call
