### ISSUE TITLE
Manage state for each pipeline request

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#55]
As a Pipeline Runner/ HKube Manager I want that HKube will manage state for each pipeline request, so that I can understand quickly the execution status of the request.

**The following states will be managed:**
Received - upon receiving pipeline request
Handled - the execution of one of the pipeline's algorithms started
Completed - the execution of all pipeline's algorithms was completed successfully
Failure - pipeline execution failed (e.g. one of its algorithm execution failed)

**Comment by eytangro** [comment]
TID-70

**Comment by tamir321** [comment]
# pipeline state management  Test

File:tid_70.js
describe : "TID-70- pipeline state management (git 55)"

Test | description 
------|----------------
Received  status-completed |execute pipeline and  validate the status
Received  status-active |execute pipeline and  validate the status
Received  status-failed |execute pipeline and  validate the status
Received  status-stop |execute pipeline and  validate the status
Received  status-pending |execute pipeline and  validate the status
