### ISSUE TITLE
add simple API for storage

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#554]

**Comment by tamir321** [comment]
swagger test was added/change

**Comment by tamir321** [comment]
# Algorithm run Test

File: swaggerCalles.js
describe : "storage git(554)"

Test | description 
------|----------------
GET /storage/infol | storage info
GET /storage/prefix/types | storage types
GET keys by path /storage/prefixes/{path} | storage prefix
GET keys by path /storage/keys/{path} | GET keys by path /storage/keys/{path}
GET storage data /storage/values/{path} | GET storage data /storage/values/{path}
GET stream data /storage/stream/{path} | GET stream data /storage/stream/{path}
GET stream data to file /storage/download/{path}| GET stream data to file /storage/download/{path}
