### ISSUE TITLE
Support using arbitrary base images

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#563]
For each supported build environment, allow using any base image (within the following limitations)
1. python: versions: 2.7, 3.5, 3.6, 3.7 based on debian linux for amd64 arch
2. nodejs: version 10 based on debian linux for amd64 arch

tasks:
- [x] add baseImage to algorithm/apply
- [x] package hkube-*-wrapper (and dependencies) for all environments in algorithm-builder docker
- [x] install dependencies from saved files
- [x] add support in hkubectl
- [ ] add support in dashboard

to test:
- [ ] all environments/all above versions
- [ ] for python, also test with ```tensorflow/tensorflow:1.15.0-py3``` and ```tensorflow/tensorflow:1.15.0```
- [ ] nice to have - test with alpine as well

**Comment by tamir321** [comment]
tested on version 1.2.35
python 2.7  - tamir321/py27
python 3.5  - tamir321/py35
python 3.6  - tamir321/py36
python 3.7  - tamir321/py37

node10 - tamir321/algoversion
