### ISSUE TITLE
Manage state for each algorithm in pipeline request

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#57]
As a Pipeline Runner/ HKube Manager I want that HKube will manage state for each algorithm in pipeline request, so that I can understand quickly the execution status of the request.
**The following states will be managed:**
Pending - upon receiving the algorithm request
Active - the execution of algorithm started
Completed - the execution of the algorithm was completed successfully
Failed -algorithm execution failed (e.g. SW exception or the algorithm execution was completed and returned failure value)
Stopped - algorithm execution stopped due to stop request (e.g. P.L failure or user request to stop the P.L)

**Comment by eytangro** [comment]
TID-460
