### ISSUE TITLE
Cache storage data in worker

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#576]
When handling batch algorithm processing, the complete input data (including the data to be processed by the rest of the parallel algorithms) is obtained from storage upon the beginning of every algorithm in the batch.

To enhance performance, cache the last processed data from the storage in the worker, so that it will be obtained once per worker.

**Comment by eytangro** [comment]
TID-630

**Comment by tamir321** [comment]
# worker cache Test

File: cache_test.js
describe : "'Test worker cache'"

Test | description 
------|----------------
storage get amount| validate that the worker uses cache mechanism and does not read data from storage if its exists in cache
