### ISSUE TITLE
Pipeline's algorithms will be executed by priority

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#58]
As a HKube Manager I want that pipeline's algorithms will be executed by priority.
---
**User Story implementation details:**
1. The priority of algorithm is calculated using a linear function which use the following parameters:
1.1 Priority of the pipeline type (1-5) - system parameter managed per pipeline type
1.2 Size of the algorithm batch: 
1.2.1 bigger batch will get lower priority
1.2.2 batch size will be taken as the remaining amount of algorithms to be executed
1.3 The pending time of the algorithm - bigger pending time will get higher priority
2. Hkube will calculate the priority of algorithm every P6 (system parameter) seconds. The periodic calculation is needed since pending time is updated and the size of the remaining batch algorithms to be executed is decreasing
3. The weights for the priority parameters will be taken from configuration file (P1).
4. Algorithms requests will be executed according to their priority. 
5. Algorithm requests with the same priority will be executed in FIFO order.

**Comment by eytangro** [comment]
TID-440
