### ISSUE TITLE
add form data to components in the UI

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#582]
**Is your feature request related to a problem? Please describe.**
i would like to create automated tests to the UI. in order to do so in a comfortable manner i would you to add some formData to some components in the ui in order to at least check that i can run the automated test and debug it with ease 

**Describe the solution you'd like**
i have created a simple scenario for the prof of concept:

- [ ] go to pipelines page
- [ ] search for pipeline by name in the search bar
- [ ] click on the run button of a pipeline
- [ ] click on the "run" button in the json that was opened
- [ ] assert the message that the pipeline started appeared
- [ ] go to the jobs page
- [ ] assert the status bar is present and get its text value

**Additional context**
please add the formData to those DOM element i need interaction with so i can automate the scenario above.
i think using the key "testId" is a good idea but please feel free to propose other key

**Comment by denvash** [comment]
If still relevant please visit our office
