### ISSUE TITLE
input for an algorithm after skipped node

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#583]
**HKube micro-service**
worker / pipeline driver

**Describe the bug**
if the first node was skipped for some reason and a second node gets its input from the previous (skipped) node the algorithm dosent run

**Expected behavior**
i would like to see the pipeline stop and show an error message

**To Reproduce**
run the following pipeline:

`
{
    "name": "countEven",
    "nodes": [{
            "nodeName": "even",
            "algorithmName": "eval-alg",
            "input": [
                "#@flowInput.nums"
            ],
            "extraData": {
                "code": [
                    "function split(input) {",
                    "return (input[0][0] + input[0][1]) % 2 === 0",
                    "}"
                ]
            }
        },
        {
            "nodeName": "count",
            "algorithmName": "eval-alg",
            "input": [
                "@even"
            ],
            "extraData": {
                "code": [
                    "function count (input) {",
                    "let counter=0",
                    "for (let i=0 ; i<input[0].length ; i++){",
                    "if (input[0][i]){",
                    "counter++}}",
                    "return counter",
                    "}"
                ]
            }
        }
    ],
    "flowInput": {
        "nums": []
    }
}
`

**Comment by NassiHarel** [comment]
Fixed

**Comment by tamir321** [comment]
tested on version 1.2.28
