### ISSUE TITLE
algorithm versions list is copied to all open algorithms

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#593]
**HKube micro-service**
Dashboard
**Describe the bug**
versions  are copied from on algorithm to the other 

**Expected behavior**
each algorithm should displayed it own version list

**To Reproduce**
1. Go to Algorithm page
2. expend the first algorithm - the version list is display
3. without closing the first algorithm expend the second algorithm - the second algorithm version list is display in  both algorithm
![bug.jpg](https://images.zenhubusercontent.com/5ddb91c470bd590001fbdfae/1d1b6410-f910-4cbd-8c20-88f5532c8c55)

**Screenshots**

**Additional context**

**Comment by denvash** [comment]
Thank you for the issue, its already fixed and waiting for approval in [this PR](https://github.com/kube-HPC/simulator/pull/71).
