### ISSUE TITLE
copy worker ID to clipboard - from Node Information form

### ISSUE THREAD

**Issue by dannysh3** [kube-HPC/hkube#598]
**Is your feature request related to a problem? Please describe.**
Required in order to find the worker ID in KIBANA

**Describe alternatives you've considered**
Currently we dont have direct solution we bypass by searching for pod ID

**Comment by yehiyam** [comment]
implemented in dashboard
![Screenshot from 2020-01-14 15-55-23](https://user-images.githubusercontent.com/6139491/72350057-57b3ca80-36e6-11ea-98d2-a3ed29964826.png)


![Screenshot from 2020-01-14 15-56-12](https://user-images.githubusercontent.com/6139491/72350090-68fcd700-36e6-11ea-92d4-7c4ec79f520e.png)

**Comment by tamir321** [comment]
tested in 1.2.28
