### ISSUE TITLE
results responses comes with jobid object

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#6]
the get results with web hook comes with job id object.

[
:   {
:   :   "**jobId**":"bigevaltest:e44b1ae9-b10b-4a31-8359-498805d5c093",
:   :   "timestamp":"2018-01-07T11:55:12.661Z",
:   :   "execution_id":"bigevaltest:e44b1ae9-b10b-4a31-8359-498805d5c093",
:   :   "pipeline":"bigevaltest",
:   :   "data":
:   :   {
:   :   :   "result":
:   :   :   [
:   :   :   :   {
:   :   :   :   :   "nodeName":"evalmul",
:   :   :   :   :   "algorithmName":"eval-alg",
:   :   :   :   :   "result":24
:   :   :   :   }
:   :   :   ],
:   :   :   "status":"completed"
:   :   }
:   }
]

**Comment by NassiHarel** [comment]
execution_id has been removed
