### ISSUE TITLE
Cancel pipeline execution, if one of its algorithms completed its execution with failure

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#60]

**Comment by eytangro** [comment]
TID-110

**Comment by tamir321** [comment]
# batchTolerance Test

File: tid_110.js
describe : "TID_110 - batchTolerance  -  algorithm completed with failure (git 60 86)"

Test | description 
------|----------------
should complete the pipeline, 100 percent tolerance with one fail | execute  pipeline validates no error
should fail the pipeline, 20 percent tolerance with one fail| execute  pipeline validates pipeline error
should complete the pipeline, 60 percent tolerance with one fail| validates pipeline completed
should fail the pipeline, -2 percent tolerance with one fail | validate the pipeline fail
should fail the pipeline, 101 percent tolerance with one fail | validate the pipeline fail
should fail the pipeline, 20.6 percent tolerance with one fail | validate the pipeline fail
should fail the pipeline,"twenty" percent tolerance with one fail | validate the pipeline fail
