### ISSUE TITLE
Add TTL for each Algorithm

### ISSUE THREAD

**Issue by dannysh3** [kube-HPC/hkube#601]
**Is your feature request related to a problem? Please describe.**
Currently there is TTL on the pipe scope. we need TTL at algorithm scope

**Describe alternatives you've considered**
currently this implemented on each algorithm,. should be part of infrastructure

**Comment by yehiyam** [comment]
same as #342

**Comment by yehiyam** [comment]
api:
 * add ttl parameter to node in pipeline
   * ttl value in seconds
   * value of 0 - disables ttl for this node
   * default value is 0
  * on ttl expiry
    *  _stop_ is sent to the algorithm
    * the node is marked as failed

**Comment by yehiyam** [comment]
implemented by #668

**Comment by tamir321** [comment]
tested on version 1.2.35 
automated tests added to algorithm_test.js
