### ISSUE TITLE
Algorithm retry

### ISSUE THREAD

**Issue by dannysh3** [kube-HPC/hkube#602]
**Is your feature request related to a problem? Please describe.**
As part of current policy,in case of network dis-communication, the mechanism of retry does not apply.
We wish that the retry mechanism will be applied no matter of the failure reason

**Comment by NassiHarel** [comment]
We decided to add retry on node level:
```json
{
                "nodeName": "green",
                "algorithmName": "green-alg",
                "input": [
                    "@flowInput.files.link"
                ],
                "retry": {
                    "policy": "onFailure",
                    "limit": 3
                }
            }
}
````

**Comment by tamir321** [comment]
automation test created .

**Comment by tamir321** [comment]
# Algorithm retry Test

File: algorithm_retry.js
describe : "pipeline Types" / "pipelina crash"

Test | description 
------|----------------
'rawPipeCrash no retry'| validate "Never" disable retry
'rawPipeCrash Always retry 4 time' | validate "Always" will enable retry  on carsh 
'rawPipeCrash OnCrash retry 3 time'| validate that "oncrash" enable retry 
'rawPipeCrash OnError will not  retry 3 time'| validate that "onerror" will not retry when there is crash 

describe : "pipeline Types" / "pipelina error"

Test | description 
------|----------------
'rawPipeError no retry'| validate "Never" disable retry
'rawPipeError Always retry 4 time' | validate "Always" will enable retry both on   on error
'rawPipeError OnError retry 3 time'| validate that "OnError" enable retry 
'rawPipeError OnCrash will not  retry 3 time'| validate that "OnCrash" will not retry when there is error 

describe : "pipeline Types" / "'pipeline Error and batchTolerance '"

Test | description 
------|----------------
'rawPipeError one retry batchTolerance =80'| validate that Error retry  does not efface  batchTolerance
''rawPipeError no retry batchTolerance =80'' | validate that Error no retry  does not efface  batchTolerance
'rawPipeCrash one retry batchTolerance =80'| validate that Crash retry  does not efface  batchTolerance
''rawPipeCrashno retry batchTolerance =80'' | validate that Crash no retry  does not efface  batchTolerance
