### ISSUE TITLE
Cancel pipeline execution, if the maximum time to receive pipeline result exceeded

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#61]
As a HKube Manager I want that HKube will cancel pipeline execution, if the maximum time to receive pipeline's result exceeded, so that HKube will be able to release the pipeline resources and hence use the system resources efficiently.
---
**User Story implementation details:**
1. Maximum time to receive result for pipeline request is optional parameter of pipeline request. 
2. Maximum time to receive result is measured from the time the pipeline request was received till the time the pipeline's result is ready.
3. Cancel action is detailed in #42
4. Cancel reason will be detailed in the pipeline log as maximum time to receive result exceeded.

**Comment by eytangro** [comment]
TID-480
