### ISSUE TITLE
Add property "Tags" & "Types" for each pipeline execution

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#614]
**Is your feature request related to a problem? Please describe.**
This will help us to filter jobs by tags in the Hkube Dashboard

**Describe the solution you'd like**
Every pipeline execution will have types: ['raw', 'stored', 'cron', 'sub-pipeline'] - defined by Hkube
Every pipeline execution can/cannot have tags: ['gpu', 'tensor'] - defined by user

**Comment by tamir321** [comment]
# pipeline Types Test

File: pipeline_tests.js
describe : "pipeline Types"

Test | description 
------|----------------
type= Triger | execute trigger pipeline
type= raw | execute raw pipeline
type= Sub-pipeline | execute piprline that lanunch subpipeline
type= stored | execute stored piprline
type = cron  internal | execute crone pipeline
