### ISSUE TITLE
Stop pipeline while running "results" status is completed

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#620]
**HKube micro-service**
api server

**Describe the bug**
Stop pipeline while running "results" status is completed

**Expected behavior**
should be the same as "status"  - "stopped"

**To Reproduce**
1. Start job 
2. Stop the job while running 
3. check the result status
![1.jpg](https://images.zenhubusercontent.com/5ddb91c470bd590001fbdfae/026b9e81-7b70-4a4d-8021-7c70d868a68d)

**Screenshots**

**Additional context**

**Comment by NassiHarel** [comment]
Upgrade to the latest version, should be resolved...

**Comment by tamir321** [comment]
tesed
