### ISSUE TITLE
Algorithm version window display other algorithms version of similar algorithm names

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#624]
**HKube micro-service**
`Dashboard`

**Describe the bug**
If Algorithm name is a substring of another algorithm name . in the "Algorithm Version" it displays its own version and the other algorithm versions 

**Expected behavior**
display only the relevant  versions

**To Reproduce**
1. Create an algorithm from image with the name: "alg"  use image "eytang/versatile-alg:v1.5"
2. Create an algorithm from image with the name: "alg1"  use image "tamir321/versatile:02"
3. expand "alg" version  -  the two versions are displayed  
![algorithm.jpg](https://images.zenhubusercontent.com/5ddb91c470bd590001fbdfae/23c4b3a0-8d5a-4fb4-bce2-fc9a40f3e946)

**Comment by denvash** [comment]
Fixed and checked on `1.2.28v`
