### ISSUE TITLE
workers of a batch in a failed pipeline still running

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#638]
**HKube micro-service**
pipeline driver
**Describe the bug**
a pipeline that failed during a batch the workers of the bach continue cun  
**Expected behavior**
all jobs should be deleted after pipeline failure
**To Reproduce**
1. run pipeline with a batch and an algorithm, that run in the same time, make the single algorithm fail, the pipeline will change the status to failed but the algorithm queue of the batch will continue releasing jobs

**Comment by NassiHarel** [comment]
Please assign someone, please provide the pipeline descriptor.

**Comment by tamir321** [comment]
duplicate 686
