### ISSUE TITLE
 pre schedule of algorithm that timed out and exited with non 0 code 

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#639]
**HKube micro-service**
not sure
**Describe the bug**
more that one instance of a worker per job

**Expected behavior**
one instance per job
**To Reproduce**
run pipeline with pre-schedule (at least two nodes in a row)
make the first node to run for longer than the algorithm timeout.
in the other algorithm make bug while exiting

**Comment by NassiHarel** [comment]
add pipeline json please
