### ISSUE TITLE
Retry algorithm execution, if system resource error (e.g. VM/ Docker failure) occurred during the algorithm execution

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#65]
As a HKube Manager I want that HKube will retry algorithm execution, if system resource error (e.g. VM/ Docker failure) occurred during the algorithm execution. 
The motivation: System resource error handling.
---
**User Story implementation details:**
The information written to the sytem log will include the following:
1. General pipeline details, see REQ_73
2. Event description: Algorithm retry due to resource error, including the algorithm ID.

**Comment by eytangro** [comment]
TID-111
