### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#652]
I think that the tensorboard API needs  re-design: why?
- Now the Api exposes 3 types of start board, if we will add comparisons between pipelines/jobs/nodes/tasks you will have to add more APis, or maybe it will be impossible to do it because the API is relying on the route params.
- Need to fetch/store from 3 different etcd paths to get all boards, if we will add comparison you need more paths, how you will stop board with comparison if you only rely on pipelineName, jobid, taskid?
- On client - you need to call to 3 different apis for same thing.
- If we show list of tensorboards, and the user want to stop one of them, it is very unintuitive to choose which API he should call to, because there are 3 types.
- if you don’t rely on boardId how you will stop a comparison board? How you will find it on etcd? Impossible.

I suggest:
- Need to rely only on boardId.
- To check if board already exists get all boards and find it by params.
- Need to make the API more agile to compare jobs, pipelines, nodes, tasks.

There should be only one API for start tensorboard, this API should accept a list of 
- PipelineName
     - NodeName - list
     - JobId -list
     - TaskId - list

and return boardId.

Avoiding the need for boardId now will cost much more later.
Also “Keep it simple” - Like there is no stop raw pipeline, stop cron pipeline or stop stored pipeline, there shouldn’t be for boards.

**Comment by tamir321** [comment]
# Algorithm run Test

File: pipeline_tests.js
describe: "pipeline Types"
need to add test to create board and validate that it was created properly

Test | description 
------|----------------
type = raw tensor | execute tensor pipeline
