### ISSUE TITLE
cannot create storage buckets when clusterName has a period in the name

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#655]
**HKube micro-service**
mostly storage-manager

**Describe the bug**
If CLUSTER_NAME env has a period (.) in the name, s3 bucket creation fails in azure

**Comment by NassiHarel** [comment]
@yehiyam solved?

**Comment by yehiyam** [comment]
no, but currently we are not working in Azure. Didn't test it yet in AWS
