### ISSUE TITLE
Graph is Unreadable in some cases

### ISSUE THREAD

**Issue by amiryi365** [kube-HPC/hkube#656]
**hkube version: 1.1.171v**
**Is your feature request related to a problem? Please describe.**
For some kinds of pipelines, the graph is unreadable and should be improved!
Take a look at the graphs of the 2 attached pipelines (both represent real pipelines in my project):
**graph_to_improve.txt:** I can't understand the dependencies; arrows run over others.
**streached_graph.txt**: some arrows are streached for no reason.

**Describe the solution you'd like**

- Enable to rotate the graph by 90' (automatic or manualy).
It's useful when one dimension size is much bigger than the other.

- Use the whole area for the graph in case the graph is bigger than X nodes, etc.

- Solve the streaching problem.

**Describe alternatives you've considered**
NA

**Additional context**
See attached pipelines
[graph_to_improve.txt](https://github.com/kube-HPC/hkube/files/4060041/graph_to_improve.txt)
[streached_graph.txt](https://github.com/kube-HPC/hkube/files/4060043/streached_graph.txt)
![graph_to_improve](https://user-images.githubusercontent.com/34741654/72359567-2abbe380-36f7-11ea-8212-5e47d9b94a87.png)
![streached_graph](https://user-images.githubusercontent.com/34741654/72359576-2e4f6a80-36f7-11ea-9327-8f543c253355.png)

**Comment by denvash** [comment]
Added feature for choosing a graph direction.

**Comment by tamir321** [comment]
tested on  "systemVersion": "v1.3.27",
