### ISSUE TITLE
Graph nodes color is sometimes wrong

### ISSUE THREAD

**Issue by amiryi365** [kube-HPC/hkube#657]
**hkube version: 1.1.171v**
**HKube micro-service**
Dshboard

**Describe the bug**
Sometimes a node's color in the graph doesn't fit the task state, e.g. the task failed but the color is green.

**Expected behavior**
Graph node's color should reflect the task state in one-to-one mapping.

**To Reproduce**
I can't tell exactly the scenarios it's getting wrong. But it happens a lot, also for non-batch nodes.
Usually when it happens: the pipeline's status may be "failed", no graph color is red, but one green node has a "failed" status (I can see it when I click on the node)

**Comment by NassiHarel** [comment]
Fixed in 1.2.0v

**Comment by tamir321** [comment]
tested on version 1.2.35
