### ISSUE TITLE
Algorithm version is not specified in dashboard "Worker" details

### ISSUE THREAD

**Issue by amiryi365** [kube-HPC/hkube#658]
**hkube version: 1.1.171v**
**Is your feature request related to a problem? Please describe.**
In Dashboard "workers" page, when I click a worker the worker Alg. version is not specified.
It's makes it harder to handle with #319

**Describe the solution you'd like**
Add Alg. version.

**Describe alternatives you've considered**
NA

**Comment by yehiyam** [comment]
fixed in version 1.2
