### ISSUE TITLE
Missing useful batch operations for multiple batch parameters

### ISSUE THREAD

**Issue by amiryi365** [kube-HPC/hkube#660]
**hkube version: 1.1.171v**
**Is your feature request related to a problem? Please describe.**
If there's more than one batch parameter per node, the behavior is strange and not useful,
i.e. for p1=[1,2,3] and p2=[A,B,C] batch params, it would have 6 instances:
[1, [A,B,C]], [2, [A,B,C]], [3, [A,B,C]], [[1,2,3], A], [[1,2,3], B], [[1,2,3], C]

**Describe the solution you'd like**

1. One useful batch operation is **Cartesian-Multiplication**, e.g. for the example above I'll get 9 instances: [1, A], [2, A], [3, A], [1, B], [2, B], [3, B], [1, C], [2, C], [3, C]
This operation would have p1_size*p2_size tasks.
**It seems to be the regular batch behavior!**

1. Another useful operation would have instance for each index in the batch param's list,
e.g. in the example: [1, A], [2, B], [3, C]
This operation requires that all batch params would have the same size.
It's very useful for me, as I wrote "generic" algorithms, when batch param is not some index, but something like feature name, DB table name, etc. Using such operation I can create several features by batch of generic feature creation Alg.

**You can have different batch symbols for different operations.**

**Describe alternatives you've considered**
Alternative to operation 1 is having only p1 as batch, but then I should duplicate it for each p2 value.
Alternative to operation 2 is sending a list of lists as parameter, but then I need to get all params from input param by index (it's especially not easy to combine with my params infrastructure which automatically loads ref params by type).
Another alternative (which I used) is having an "internal batch") params, means I send p1 as batch and p2 as a list (not batch), and get appropriate p2 value by batch index. This is not ideal either.

**Comment by NassiHarel** [comment]
@amiryi365 @yehiyam 

You only mentioned Cartesian-Multiplication What about Matrix-Multiplication?

```
{
    "name": "matrix-batch",
    "nodes": [
        {
            "nodeName": "one",
            "algorithmName": "eval-alg",
            "input": [
                "#[1...10]",
                "#11...20]",
                "#[21...30]"
            ]
        }
    ]
}
```
