### ISSUE TITLE
Missing easy access to tasks logs after worker is down

### ISSUE THREAD

**Issue by amiryi365** [kube-HPC/hkube#661]
**hkube version: 1.1.171v**
**Is your feature request related to a problem? Please describe.**
When Alg. worker gets down (few min after completing), the algorithm log is no longer available through the graph->node-click->log.

**Describe the solution you'd like**
We expect to have access to task log several hours after it completed, so we can debug easily.

**Describe alternatives you've considered**
Alternatives are using "kubectl logs" or kibana filter - **both are clumsy!**

**Comment by NassiHarel** [comment]
The logs are written also in ES, and we have API for it.
Ask @NassiHarel OR @yehiyam

**Comment by NassiHarel** [comment]
@amiryi365  We now support logs view from ES. closing issue.
