### ISSUE TITLE
Can't get result's indexed item

### ISSUE THREAD

**Issue by amiryi365** [kube-HPC/hkube#662]
**hkube version: 1.1.171v**
**Is your feature request related to a problem? Please describe.**
Sometimes I run a batch of some "generic algorithm" (see #660), but another node depends on specific batch instance result (there's also a non-batch case, or flowInput ref case).
input syntax supplies no way to define an indexed item from result list.

**Describe the solution you'd like**
I would like something like: @SomeNode[2] which means getting the 2nd (or 3rd?) item of SomeNode's result.

**Describe alternatives you've considered**
I have no choice but having a separate node outside of the batch for each task I need to get it's specific result. **It makes the pipeline more complex.**

**Comment by NassiHarel** [comment]
Instead of @SomeNode[2], try @SomeNode.2
