### ISSUE TITLE
Python Wrapper: get access to pipeline's flowInput

### ISSUE THREAD

**Issue by amiryi365** [kube-HPC/hkube#663]
**hkube version: 1.1.171v**
**Is your feature request related to a problem? Please describe.**
Pipeline's flowInput is a great place to put a common info to be used in the pipeline (referenced from input).
When I run a pipeline in the UI it gives me the original pipeline's flowInput, and I can change whatever I want and run it.
I want the same option for running a subpipeline from an algorithm,
i.e. run it with it's original flowInput, merged with my changes.

**Describe the solution you'd like**
I suggest a change in the **hkube_python_wrapper** package: 
`hkube_api.start_stored_subpipeline(name, flowInput) `
would change to:
`hkube_api.start_stored_subpipeline(name, flowInput_change) `
The difference is that now it would take the original flowInput of the subpipeline as a base, and automatically merge my flowInput_change into it (actually change only behavior, not api).

**Describe alternatives you've considered**
Alternative is getting the pipeline json manually by REST api, then extracting flowInput and merge it with my changes, then call the current start_stored_subpipeline().
That is much more complex.

**Additional context**

**Comment by NassiHarel** [comment]
@yehiyam @amiryi365 
Solved, waiting for PR

**Comment by tamir321** [comment]
tested on  "systemVersion": "v1.3.27",
