### ISSUE TITLE
Add pipeline descriptor

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#67]
As a Pipeline Builder I want to be able to add pipeline descriptor to the pipeline's Repository.
---
**User Story implementation details:**
1. Upon reception of add pipeline request, HKube will perform the following validation checks:
1.1 Verify that there isn't another pipeline descriptor with the same name in the P.L repository, so the Pipeline Builder won't override by mistake another pipeline descriptor.
1.2 Verify that all of the algorithms which are used in the pipeline descriptor are installed in the system.
2. If one of the validation checks will fail, HKube will response with error and appropriate error description.
3. If all the validation checks will pass, HKube will add the pipeline descriptor to the P.L repository.

**Comment by eytangro** [comment]
TID-320

**Comment by eytangro** [comment]
all issues with asserting that all algorithms are present,
are being closed for now (only if they pass without this requirement). adding an issue that this task should be implemented .
once the requirement is implemented a test will be written and tested as part of this test

**Comment by tamir321** [comment]
# Fetch all pipeline descriptorsTest

File: tid_310.js
describe : "pipeline actions"

Test | description 
------|----------------
TID-340- get all pipeline (git 70 41)  | validate  Fetch all pipeline 
TID-330- delete pipeline (git 69 41) | validate delete pipeline
TID-320 add the same pipeline twice (git 67 41) | validate that cant have two pipelines with the same name
