### ISSUE TITLE
Missing option for complete pipeline result including non-final nodes

### ISSUE THREAD

**Issue by amiryi365** [kube-HPC/hkube#673]
**hkube version: 1.1.171v**
**Is your feature request related to a problem? Please describe.**
I run subpipeline, then I have more nodes (or subpipelines) that depend on different subpipeline nodes result. **Dependency includes also non-final nodes** in the subpipeline.
I have an Algorithm which calls the subpipeline, then collect its node results and return this.
There's no way (in this version) to get the non-final nodes results.
Also, I need an **access by name** to the results (e.g. `@SubpipeNode.Node1` would give the result of Node1 in the subpipeline), so other nodes/subpipelines can depend on them.

**Describe the solution you'd like**
Best solution is having a flag for that in hkube_python_wrapper:
`subpipe_response = hkube_api.start_stored_subpipeline(name, flowInput, blocking=True, 
                                                                                            include_non_final=True)`

**Describe alternatives you've considered**
Currently I'm forced to create another final node for each non-final node I need in the rest of the flow - just an eval-alg based echo function that returns the result as-is.
**That's very clumsy and make the graph even more unreadable for no reason!**

**Additional context**

**Comment by yehiyam** [comment]
implemented in #685 
the user can specify, for each node in the pipeline, it they want to include the result of this node in the final result.
sink nodes are always included

**Comment by tamir321** [comment]
tested on version 1.2.35
automated tests added to pipeline_test.js

**Comment by tamir321** [comment]
# pipline  node include In Results Test

File: pipeline_test.js
describe : "pipeline includeInResults"

Test | description 
------|----------------
yellow node includeInResults = true| validate that the pipeline result contains the inner node result and the final result
yellow node includeInResults = false| validate that the pipeline result contains only the final result
