### ISSUE TITLE
Batch  on Batch

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#676]
**HKube micro-service**
worker

**Describe the bug**
pipeline with two nodes 
the second node input is the executing batch the first node results
if the first batch partly fail 1 out of 6 .
the second node fail totally fail 

**Expected behavior**
the second node should execute on the available node one results

**To Reproduce**
execute the following pipeline
```json
{
    "name": "retrytest-oncrash",
    "description": "",
    "nodes": [
        {
            "nodeName": "one",
            "algorithmName": "eval-alg",
            "input": [
                "#@flowInput.inp"
            ],
            "retry": {
                "policy": "Never",
                "limit": 3
            },
            "extraData": {
                "code": [
                    "function exit(input) {",
                    "if(input !=1){",
                    "process.exit(input)} }"
                ]
            },
            "metrics": {
                "tensorboard": true
            }
        },
        {
            "nodeName": "two",
            "algorithmName": "eval-alg",
            "input": [
                "#@one"
            ],
            "retry": {
                "policy": "OnCrash",
                "limit": 3
            },
            "extraData": {
                "code": [
                    "(input) =>{return 42}"
                ]
            },
            "metrics": {
                "tensorboard": true
            }
        }
    ],
    "flowInput": {
        "inp": [ [1],[1],[0],[1],[1],[1]]
    },
    "options": {
        "batchTolerance": 80,
        "concurrentPipelines": 10,
        "progressVerbosityLevel": "info",
        "ttl": 3600
    },
    "priority": 3
}
```

**Comment by NassiHarel** [comment]
The bug is related only to batch after batch:
here is another example that node two has failed to run:
{
    "name": "retrytest-oncrash",
    "nodes": [
        {
            "nodeName": "one",
            "algorithmName": "eval-alg",
            "input": [
                "#[0...10]"
            ],
            "extraData": {
                "code": [
                    "function throwError(input) {",
                        "if(input[0] % 2 === 0) {",
                            "throw new Error('error on eval')",
                    "} }"
                ]
            }
        },
        {
            "nodeName": "two",
            "algorithmName": "eval-alg",
            "input": [
                "#@one"
            ]
        }
    ]
}

**Comment by tamir321** [comment]
tested on version 1.2.35
