### ISSUE TITLE
Update pipeline descriptor

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#68]
As a Pipeline Builder I want to be able to update pipeline descriptor which exists in the pipeline's Repository. 
---
**User Story implementation details:**
1. The update of pipeline descriptor will affect only on new requests for this pipeline.
2. Upon reception of update pipeline request, HKube will perform the following validation checks:
2.1 Verify that there exists a pipeline descriptor with the name in the request.
2.2 Verify that all of the algorithms which are used in the pipeline descriptor are installed in the system.
3. If one of the validation checks will fail, HKube will response with error and appropriate error description.
4. If all the validation checks will pass, HKube will update the pipeline descriptor in the P.L repository.

**Comment by eytangro** [comment]
TID 320
