### ISSUE TITLE
Delete pipeline descriptor

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#69]
As a Pipeline Builder I want to be able to delete a pipeline descriptor by pipeline's name.
---
**User Story implementation details:**
1. Upon reception of delete pipeline request, HKube will verify that there exists a pipeline descriptor with the name in the request
2. If the validity check will fail, HKube will response with error and appropriate error description.

**Comment by eytangro** [comment]
TID 330

**Comment by tamir321** [comment]
# Fetch all pipeline descriptorsTest

File: tid_310.js
describe : "pipeline actions"

Test | description 
------|----------------
TID-340- get all pipeline (git 70 41)  | validate  Fetch all pipeline 
TID-330- delete pipeline (git 69 41) | validate delete pipeline
TID-320 add the same pipeline twice (git 67 41) | validate that cant have two pipelines with the same name
