### ISSUE TITLE
Add Trigger type to pipelines Types

### ISSUE THREAD

**Issue by denvash** [kube-HPC/hkube#691]
![image](https://user-images.githubusercontent.com/27515937/73603981-c3c17a00-4592-11ea-8934-497dc1be5c83.png)

- [ ] Add `pielineTypes.TRIGGER` to `@hkube/consts`

**Comment by tamir321** [comment]
# Algorithm run Test

File: pipeline_tests.js
describe : "pipeline Types"

Test | description 
------|----------------
type= Triger | execute trigger pipeline

**Comment by tamir321** [comment]
# git hub and lab Test

File: algorithmBuild .js
describe: "git hub and git lab algorithm builds (git 506)"

Test | description 
------|----------------
build github master algorithm| build github master algorithm
build github branch algorithm| build github branch algorithm
build gitlab master algorithm|build gitlab master algorithm
build gitlat branch algorithm|build gitlat branch algorithm
test webhook github (git 518)| test git lab web hook 
test webhook gitlab (git 518)|test webhook gitlab (git 518)

**Comment by tamir321** [comment]
# stop pipeline Test

File: tid_50.js
describe : "stop pipeline while its runing"

Test | description 
------|----------------
should stop the pipeline while running (git 42) | start and stop piprline while running
