### ISSUE TITLE
Fetch all pipeline descriptors

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#70]
As a Pipeline Runner I want to be able to fetch all the pipeline descriptors which exists in the pipeline's Repository, so I can know which pipeline descriptors are supported.

**Comment by eytangro** [comment]
TID 340

**Comment by tamir321** [comment]
# Fetch all pipeline descriptorsTest

File: tid_310.js
describe : "pipeline actions"

Test | description 
------|----------------
TID-340- get all pipeline (git 70 41)  | validate  Fetch all pipeline
