### ISSUE TITLE
crone and trigger pipeline cant get pipelines/results and /pipelines/status by pipeline name

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#703]
**HKube micro-service**
API-server

**Describe the bug**
after pipeline was executed by trigger or crone try to get result using
trigger example
strore the following pipeline
```json
{
    "name": "trigger-test",
    "description": "",
    "nodes": [
        {
            "algorithmName": "black-alg",
            "input": [],
            "nodeName": "ye"
        }
    ],
    "flowInput": {},
    "webhooks": {
        "progress": "http://1",
        "result": "http://1"
    },
    "triggers": {
        "cron": {
            "pattern": "0 * * * *",
            "enabled": false
        },
        "pipelines": [
            "simple"
        ]
    },
    "options": {
        "batchTolerance": 100,
        "concurrentPipelines": 10,
        "progressVerbosityLevel": "info",
        "ttl": 3600
    },
    "priority": 3,
    "experimentName": "main"
}
```

execute simple pipeline 
trigger-test will be executed
try to get trigger result by using
https://10.32.10.11/hkube/api-server/api/v1/pipelines/results?name=trigger-test
get error pipeline results trigger-test Not Found

when trying to get "simple" result/status you will get both simple and trigger-test pipeline results
"https://10.32.10.11/hkube/api-server/api/v1/pipelines/status?name=simple&limit=8"

**Comment by NassiHarel** [comment]
The cron results/status has different API
https://10.32.10.11/hkube/api-server/api/v1/cron/status?name=my-cron

**Comment by tamir321** [comment]
tested systemVersion: "v1.3.7",
