### ISSUE TITLE
github private  repository need to add username 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#715]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
in order to use github private  repository it require username and token/password currently you can only add token and not the user name
need to add username to the new algorithm form

![newalg.jpg](https://images.zenhubusercontent.com/5ddb91c470bd590001fbdfae/af8b09a6-0bf2-4ffc-93a4-b103955d743f)

**Comment by NassiHarel** [comment]
There is no need for username, only token

**Comment by tamir321** [comment]
tested on version 1.2.39 (on the CICD )
