### ISSUE TITLE
HKube execution overheads

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#75]
As a HKube Manager/ Pipeline Builder, I want that HKube execution overheads derived from HKube infrastructure will be on average 10 percent of the pipeline handling time.
---
**User story implementation details:**
1. Definitions:
1.1. Execution overheads = Pipeline handling time - execution time of all the P.L algorithms.
1.2. Pipeline handling time = From the time the pipeline's request was received till its result is written.
1.3. Execution time of P.L algorithm = From the time the execution of the algorithm started till the time the result of the algorithm is written.
2. Execution overheads doesn't include the startup time of the container - depends in the containers size, network performance, etc.
3. Execution overheads doesn't include the time needed to read the inputs for each algorithm in the pipeline.
4. Execution overheads depends in HW resources availability, meaning that if there are less available resources then the pending time for execution of algorithm will be higher.
5. The minimum execution overhead for algorithm will be 1 second. 
6. In case there are few algorithms which are executed in parallel, then the total overhead will be equal to max (10 percent of the execution time of each of these algorithms)

**Comment by eytangro** [comment]
TID_170
