### ISSUE TITLE
github build  ignor the commitid

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#770]
**HKube micro-service**
API server

**Describe the bug**
when creating algorithm from github . its take the latest version and ignor the commit id enterd

the github swgger "/builds/webhook/github" does not work should be change to:
.post('/builds/webhook/github')
            .type('form')
            .set('content-type', 'application/x-www-form-urlencoded')            
            .send ({'payload': JSON.stringify(data)})

**Comment by NassiHarel** [comment]
@yehiyam @tamir321

Fixed, waiting for PR

**Comment by tamir321** [comment]
tested on systemVersion": "v1.3.22",
