### ISSUE TITLE
Fail algorithm build need to remove the Stop button

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#774]
**HKube micro-service**
if an algorithm fails to build the "Stop" button should be removed or disable (can be replaced with  rebuild button)

![40.69.222.75_hkube_dashboard_.png](https://images.zenhubusercontent.com/5ddb91c470bd590001fbdfae/6dcfe92f-37e9-4214-856b-a162ca7d5432)

**Comment by denvash** [comment]
Fixed on [#95](https://github.com/kube-HPC/simulator/pull/95)

**Comment by tamir321** [comment]
tested on 1.2.50
