### ISSUE TITLE
Unable to delete algorithm properties once added

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#792]
**HKube micro-service**
API-SERVER

**Describe the bug**
Adding props:
"algorithmEnv": {
        "DISCOVERY_TIMEOUT": 30,
        "DISCOVERY_ENABLE": "False"
}

and then unable to delete this.

**Comment by tamir321** [comment]
when editing algorithm if "algorithmEnv" exist . 
you can delete   algorithmEnv child property 
but fail to delete the entaier property
