### ISSUE TITLE
worker crashes after timeout between the worker and the algorithm

### ISSUE THREAD

**Issue by eytangro** [kube-HPC/hkube#8]
if i run a pipeline and the pipeline got stuck from some reason and didn't return an error the pipeline-driver remain stuck with this pipeline and never gets free.

**Comment by NassiHarel** [comment]
I think that for this specific case the worker should return an error.
If the worker crashed, another worker will get the job, after some retries the pipeline-driver should handle this. there are two different cased here.

**Comment by maty21** [comment]
pipeline driver doesn't get a notification in case of worker failure
