### ISSUE TITLE
High Availability for HKube infrastructure services - version 100

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#80]
As a Pipeline builder, I want that HKube will include high availability mechanism, so that algorithm developers won't need to handle this aspect.
---
**User story implementation details:**
1. HKube infrastructure services will be available immediately in case of first system failure (e.g. failure of first node in a cluster).
2. HKube will recover within one minute in case of Kubernetes management service failure. During the recovery time, HKube will continue to execute pipelines which their execution already started.
3. The recovery of the services depends in hardware availability.

**Comment by eytangro** [comment]
TID-161,
TID-211
