### ISSUE TITLE
If pipeline was unable to be executed due to resource problem the rezone should be displayed

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#803]
As a hkube operator If I executed pipeline and the system didn't have the resource to execute it
I would like to get a message that specified why it was not executed

**Comment by NassiHarel** [comment]
@tamir321 @yehiyam

fixed, waiting for PR

**Comment by NassiHarel** [comment]
@yehiyam , @maty21 

We want to fail the pipeline immediately if the resources reached the max.
