### ISSUE TITLE
High Availability for HKube DB's

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#81]
As a HKube Manager, I want that HKube will include high availability mechanism for the HKube's DBs, so that data won't be lost in case of cluster failure (e.g. electricity failure).
---
**User story implementation details:**
1. HKube's DBs include: Pipeline results, Pipeline descriptor repository and system log.
2. Data recovery of HKube's DBs won't succeeded if their storage was damaged during the cluster failure

**Comment by Ronenk5678** [comment]
Please check the following:
[ES]
[Redis]
[Etcd]

**Comment by eytangro** [comment]
TID-161
