### ISSUE TITLE
Caching Service

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#814]
We still have some problems running cached nodes, run cache on a pipeline that already ran as cached

**Comment by tamir321** [comment]
#caching (run node) test

File:node_test.js 
describe : "pipe flowInput line batch input"

Test | description 
------|----------------
caching (Run Node) batch index | build algorithm from github
caching (Run Node) flowInput batch cartesian | build algorithm from gitlab
caching (Run Node) batch + fix indexed | caching (Run Node) batch + fix indexed
caching (Run Node) batch +any| caching (Run Node) batch +any
caching (Run Node) on cached pipeline|caching (Run Node) on cached pipeline
