### ISSUE TITLE
delete pipeline should stop all active and pending pipeline 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#820]
when deleting pipeline the active and pending pipeline should be stopped

**Comment by NassiHarel** [comment]
@tamir321 @yehiyam
fixed, waiting for PR

**Comment by tamir321** [comment]
File:pipeline_tests.js 
describe : "pause_resume_pipelineas (git 529 344)"

Test | description 
------|----------------
delete pipeline stop all pipeline | delete pipeline stop all active pending pipeline
