### ISSUE TITLE
fail to build gitlab algorithm

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#822]
**HKube micro-service**
api  server

**Describe the bug**
when tring to build algorithm from gitlab you are getting 
Error response, status=500, message=TypeError: Cannot read property '0' of undefined
build the following algorithm (with or without commit/id)

```json
{
    "name": "gitlabalg",
    "cpu": 1,
    "gpu": 0,
    "mem": "256Mi",
    "minHotWorkers": 0,
    "baseImage": "",
    "options": {
        "debug": false
    },
    "gitRepository": {
        "entryPoint": "master",
        "url": "https://gitlab.com/tamir321/hkube.git",
        "commit": {
            "id": "507aa9b1db90ccda19aef145849fb18362ab1bb7"
        },
        "branchName": "master",
      
        "gitKind": "gitlab"
    }
}

**Comment by NassiHarel** [comment]
@tamir321 @yehiyam

fixed, waiting for PR

**Comment by tamir321** [comment]
tested on 
 "systemVersion": "v1.3.36",
    "fullSystemVersion": "v1.3.36-1592826366249",
