### ISSUE TITLE
pause and resume batch on batch pipeline 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#823]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
when pausing batch on batch pipeline the last batch stay Preschedule state 

run the pasueResumePipe pipeline
pause it after 3 seconded 
wait 2 minutes 
resume the pipeline
![image.png](https://images.zenhubusercontent.com/5ddb91c470bd590001fbdfae/be91cdd6-bd43-41f8-89ce-bdbda7a90f79)

```json
{
    "name": "pasueResumePipe",
    "nodes": [
        {
            "nodeName": "eval1",
            "algorithmName": "eval-alg",
            "input": [
                "@flowInput.range"
            ],
            "extraData": {
                "code": [
                    "(input) => {",
                    "const range = Array.from(Array(input[0]).keys());",
                    "return range }"
                ]
            }
        },
        {
            "nodeName": "firstbatch",
            "algorithmName": "eval-alg",
            "input": [
                "#@eval1",
                "@flowInput.inputs"
            ],
            "extraData": {
                "code": [
                    "(input,require)=> {",
                    "return new Promise((resolve,reject)=>{setTimeout(()=>resolve(4),input[1])});}"
                ]
            }
        },
        {
            "nodeName": "secondbatch",
            "algorithmName": "eval-alg",
            "input": [
                "#@eval1",
                "@flowInput.inputs",
                "#@firstbatch"
            ],
            "extraData": {
                "code": [
                    "(input,require)=> {",
                    "return new Promise((resolve,reject)=>{setTimeout(()=>resolve(4),input[1])});}"
                ]
            }
        }
    ],
    "experimentName": "main",
    "options": {
        "ttl": 3600,
        "batchTolerance": 80,
        "progressVerbosityLevel": "info"
    },
 "flowInput":{
        "range":50,
        "inputs":4000
    },
    "priority": 3
}

**Comment by tamir321** [comment]
tested on  
    "systemVersion": "v1.3.36",
    "fullSystemVersion": "v1.3.36-1592826366249",

no change the second batch stay Preschedule

![test.hkube.io_hkube_dashboard_.png](https://images.zenhubusercontent.com/5ddb91c470bd590001fbdfae/7fb973d0-0bdc-4bed-9818-6e4a692355d7)

**Comment by tamir321** [comment]
tested on 
systemVersion": "v1.3.36",
    "fullSystemVersion": "v1.3.36-1592826366249",

**Comment by tamir321** [comment]
after resuming the pipeline stay in resume status
tested on v2.0.13

**Comment by NassiHarel** [comment]
@tamir321 
2 minutes is too much.... 
you can change the `flowInput.inputs` from 4000 to 1000

**Comment by tamir321** [comment]
tested on version

systemVersion: "v2.0.22",
fullSystemVersion: "v2.0.22-1606139142985",
