### ISSUE TITLE
Debug disconnection

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#845]
When the algorithm disconnected from worker, the worker should be ready to process a new job

**Comment by tamir321** [comment]
disconnection accords in two cases:

1. while debugging worker gets "uncaugthehtException: Watcher canceled:" from the algorithm

2. while debugging stop the pipeline 

in both cases only killing the worker will enable you to restart debugging

**Comment by NassiHarel** [comment]
@tamir321 
The worker doesn't get "uncaugthehtException: Watcher canceled:" from the algorithm.
This is an ETCD Exception.
