### ISSUE TITLE
Java build logs size

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#855]
**HKube micro-service**
monitor-server 

**Describe the bug**
during building java algorithm Maven create large logs that are saved in the ETCD causing the monitor-server to fail and to the dashboard  fail to start

- monitor server should ignore build logs if they are to big

- reduce the java log size

-  save build log in storage

**Comment by yehiyam** [comment]
@golanha is this fixed?

**Comment by yehiyam** [comment]
@golanha is this fixed?
