### ISSUE TITLE
Define batch tolerance

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#86]
As a Pipeline Builder I want to be able to define batch tolerance for batch execution, so that HKube won't fail the pipeline if part of the batch algorithms failed
---
**User Story implementation details:**
1. The _Batch Tolerance_ is a threshold setting that allow to control in which percent from the batch processing the entire pipeline should be fail.
from the batch processing the entire pipeline should be fail.
2. HKube shall enable to define the batch tolerance in the pipeline descriptor.

**Comment by eytangro** [comment]
TID-110

**Comment by tamir321** [comment]
tests can be found
https://github.com/kube-HPC/hkube/issues/60
