### ISSUE TITLE
shorten job and task id

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#860]
After a short test, we can see that if we will shorten the job and task ID, we will reduce the size of storage (etcd, redis, fs, s3) by half and even more.

We will shorten the ids from 36+ chars to only 8 chars.

The job id and task id are usually go together and saved as:

cicd-hkube/main:big-batch:659daa65-a1d5-4756-adcc-26c091599a5c/green:green-alg:4b6230d0-d3b8-41ab-979e-9ff6cd947820

**Comment by tamir321** [comment]
testes on
  "systemVersion": "v1.3.92",
    "fullSystemVersion": "v1.3.92-1595420707516",
    "versions": [
