### ISSUE TITLE
Wait any transition condition of batch algorithms

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#87]
As a Pipeline Builder I want to be able to define wait any transition condition for batch algorithms.
---
**User Story implementation details:**
_Wait any transition condition means:_ successful execution of any batch algorithm will start independent successor algorithm.

**Comment by eytangro** [comment]
TID-350

**Comment by tamir321** [comment]
# wait any condition

File: tid_310.js
describe : "pipeline actions"

Test | description 
------|----------------
TID-350- wait any condition (git 87) | execute pipeline validates the result
