### ISSUE TITLE
Algorithm definition should include the output mime type  (jpg, json,txt .....)

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#877]
as a Hkube user I wold want  to define the algorithm definition  the algorithm output mime type .

- downloading the algorithm result should download the file with the define type so it is easy to view

- pipeline download result should create a zip file containing all the "last" algorithms output and one metadate file

**Comment by NassiHarel** [comment]
@tamir321 

Done: (wait for version)
downloading algorithm result: you can add property to algorithm: `downloadFileExt`
download pipeline result will be at: /api/v1/storage/download/pipeline/result/<JobId>

**Comment by tamir321** [comment]
tested on version
systemVersion: "v1.3.133",
fullSystemVersion: "v1.3.133-1601904627769",
