### ISSUE TITLE
Part or all of the inputs of algorithm are taken from indexed predecessor batch algorithms

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#88]
As a Pipeline Builder I want to be able to define that the algorithm's inputs (part or all) will be taken from indexed output of predecessor batch algorithms.
---
**User Story implementation details:**
E.g for  indexed output of predecessor batch algorithms: 
alg C receives the output of batch alg A (A1, A2, A3) and the output of batch alg B(B1, B2, B3) then 3 instances of alg C will be executed with the following input: (A1, B1), (A2,B2), (A3,B3)

**Comment by eytangro** [comment]
TID-360

**Comment by tamir321** [comment]
# indexed condition

File: tid_310.js
describe : "pipeline actions"

Test | description 
------|----------------
TID-360- indexed condition (git 88) | execute pipeline validate result
