### ISSUE TITLE
hkubectl Issues

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#881]
- [x] Execute algorithm apply missing image option​
- [x] Execute algorithm apply​ should return the build id
- [x]  Execute algorithm apply​  from file the code file is relative to the yaml file
- [x]  Execute algorithm apply should have the option to change algorithm version

- [x]  ​hkubectl config set does not work - return function

- [x]  "Hkuectl pipeline get" is the same as  to "hkubectl exec get​"

- [x]  Execute stored wait should return the jobid with the result
- [x]  Exec stop/status require “—jobId = “ (spaces before and after the equal sign)
- [x]  Hkubectl exect  --help the raw have [name] should be file name
- [x]  Execute raw pipeline execute no option for wait
- [x] Execute raw pipeline should return the result/jobid same as stored

**Comment by yehiyam** [comment]
added --json option for json output
exec raw - removed name (not needed). use -f to specify filename. You can use `hkubectl exec raw -f -` to specify input from stdin
exec stop/status - removed the --jobId param. simply run `hkubectl exec stop theJobId`
hkubectl exec get <jobId> is now the same as the api exec/pipelines/jobId

**Comment by tamir321** [comment]
tested on version

systemVersion: "v1.3.133",
fullSystemVersion: "v1.3.133-1601904627769",
