### ISSUE TITLE
python wrapper does not work with s3

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#887]
**HKube micro-service**
algorithm - python wrapper
**Describe the bug**
When using s3 the python wrapper is unable to connect to s3
The wrapper throws an error "unable to connect to http://127.0.0.1:9000"

**Expected behavior**
should connect to s3

**Additional context**
It seems that the URL in the wrapper config is read from the wrong environment variable

@tamir321 We should test Hkube using S3 and not just filesystem

**Comment by yehiyam** [comment]
fixed

**Comment by tamir321** [comment]
tested on Rafael Network
