### ISSUE TITLE
View the pipeline events in system log of HKube

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#89]
As a HKube Manager/ Pipeline Builder I want to view pipeline events in the system log of HKube, so I'll be able to identify and diagnose the source of pipeline problems.
---
**User Story implementation details:**
1. Each pipeline event in the system log will contain the following information:
1.1. ID of the pipeline request - created by HKube
1.2  ID of the algorithm request - created by HKube, relevent for events of pipeline's algorithm.
1.3. Data & Time - the date &time of the event
1.4. Description - the description of the event

**Comment by eytangro** [comment]
TID-120
