### ISSUE TITLE
hkubectl sync watch does not copy the source file to the algorithm mount storage

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#890]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
hkubectl sync watch does not copy the source file to the algorithm mount storage
the bug was caused by a fix that was made for Openshift

**To Reproduce**
execute : hkubectl sync create --entryPoint XXX --algorithmName ZZZ --folder QQQ --env python
execute : hkubectl sync watch -a ZZZ -f QQQ

make change in one of the source file 
the files are not coped to the algorithm and when executing the algorithm receiving an error for the missing files

**Comment by yehiyam** [comment]
fixed in v1.3.95.
dd
