### ISSUE TITLE
Algorithm Queue uncaughtException: Watcher canceled:

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#894]
**HKube micro-service**
Algorithm Queue

**Describe the bug**
during load Algorithm Queue fail from time to time casing the pipeline to fail:

algorithm queue error:
```json
{
"type":"algorithm-queue"
"hostName":"algorithm-queue-node-rand1-6d8b85d874-b254t"
"uptime":292436
"timestamp":1596374050832
"serviceName":"algorithm-queue"
"podName":"algorithm-queue-node-rand1-6d8b85d874-b254t"
"id":"d2ba47d8-1aab-44f8-b427-5fe080fa8d46"
"level":"error"
"message":"uncaughtException: Watcher canceled: "
}

```
worker error
```json
{
"type":"worker"
"hostName":"node-rand2-du91jnfulqzn4ch0ma1le2vb23oyel-rprtw"
"uptime":292684
"timestamp":1596374298245
"serviceName":"worker"
"podName":"node-rand2-du91jnfulqzn4ch0ma1le2vb23oyel-rprtw"
"id":"3369ee9e-77b6-4ade-be03-0ba3b4dcc01e"
"level":"error"
"message":"algorithm node-rand2 has disconnected while in working state, reason: CLOSE_ABNORMAL. status: terminated,exitCode: 1,reason: Error,startedAt: 2020-08-02T13:17:39Z,finishedAt: 2020-08-02T13:18:17Z,containerID: docker://5d0c789c875c844683ab42bc68128758948e172ff2aa524adf3a2e35b522e036"
}
````
error from algorithm 

31/07/20 23:37:28got message from worker: initialize
Info
231/07/20 23:37:28sending message to worker: initialized
Info
331/07/20 23:37:28got message from worker: start
Info
431/07/20 23:37:28sending message to worker: started
Info
531/07/20 23:37:28Segmentation fault (core dumped)
Info
631/07/20 23:37:28npm ERR! code ELIFECYCLE
Info
731/07/20 23:37:28npm ERR! errno 139
Info
831/07/20 23:37:28npm ERR! nodejs-env@1.2.1 start: `node app`
Info
931/07/20 23:37:28npm ERR! Exit status 139
Info
1031/07/20 23:37:28npm ERR!
Info
1131/07/20 23:37:28npm ERR! Failed at the nodejs-env@1.2.1 start script.
Info
1231/07/20 23:37:28npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Info
1331/07/20 23:37:28
Info
1431/07/20 23:37:28npm ERR! A complete log of this run can be found in:
Info
1531/07/20 23:37:28npm ERR! /root/.npm/_logs/2020-07-31T20_37_28_476Z-debug.log
Info
1631/07/20 23:38:13got message from worker: initialize
Info
1731/07/20 23:38:13sending message to worker: initialized
Info
1831/07/20 23:38:13got message from worker: start
Info
1931/07/20 23:38:13sending message to worker: started
Info
2031/07/20 23:38:14Segmentation fault (core dumped)
Info
2131/07/20 23:38:14npm ERR! code ELIFECYCLE
Info
2231/07/20 23:38:14npm ERR! errno 139
Info
2331/07/20 23:38:14npm ERR! nodejs-env@1.2.1 start: `node app`
Info
2431/07/20 23:38:14npm ERR! Exit status 139
Info
2531/07/20 23:38:14npm ERR!
Info
2631/07/20 23:38:14npm ERR! Failed at the nodejs-env@1.2.1 start script.
Info
2731/07/20 23:38:14npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Info
2831/07/20 23:38:14
Info
2931/07/20 23:38:14npm ERR! A complete log of this run can be found in:
Info
3031/07/20 23:38:14npm ERR! /root/.npm/_logs/2020-07-31T20_38_14_094Z-debug.log
Info
3131/07/20 23:39:04got message from worker: initialize
Info
3231/07/20 23:39:04sending message to worker: initialized
Info
3331/07/20 23:39:04got message from worker: start
Info
3431/07/20 23:39:04sending message to worker: started
Info
3531/07/20 23:39:04Segmentation fault (core dumped)
Info
3631/07/20 23:39:04npm ERR! code ELIFECYCLE
Info
3731/07/20 23:39:04npm ERR! errno 139
Info
3831/07/20 23:39:04npm ERR! nodejs-env@1.2.1 start: `node app`
Info
3931/07/20 23:39:04npm ERR! Exit status 139
Info
4031/07/20 23:39:04npm ERR!
Info
4131/07/20 23:39:04npm ERR! Failed at the nodejs-env@1.2.1 start script.
Info
4231/07/20 23:39:04npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Info
4331/07/20 23:39:04
Info
4431/07/20 23:39:04npm ERR! A complete log of this run can be found in:
Info
4531/07/20 23:39:04npm ERR! /root/.npm/_logs/2020-07-31T20_39_04_696Z-debug.log
Info
4631/07/20 23:39:51got message from worker: initialize
Info
4731/07/20 23:39:51sending message to worker: initialized
Info
4831/07/20 23:39:51got message from worker: start
Info
4931/07/20 23:39:51sending message to worker: started
Info
5031/07/20 23:39:51Segmentation fault (core dumped)
Info
5131/07/20 23:39:51npm ERR! code ELIFECYCLE
Info
5231/07/20 23:39:51npm ERR! errno 139
Info
5331/07/20 23:39:51npm ERR! nodejs-env@1.2.1 start: `node app`
Info
5431/07/20 23:39:51npm ERR! Exit status 139
Info
5531/07/20 23:39:51npm ERR!
Info
5631/07/20 23:39:51npm ERR! Failed at the nodejs-env@1.2.1 start script.
Info
5731/07/20 23:39:51npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Info
5831/07/20 23:39:51
Info
5931/07/20 23:39:51npm ERR! A complete log of this run can be found in:
Info
6031/07/20 23:39:51npm ERR! /root/.npm/_logs/2020-07-31T20_39_51_816Z-debug.log
Info

**Comment by yehiyam** [comment]
#896 should fix algorithm-queue error - needs more testing
#897 should fix `npm ERR! errno 139` error. needs to rebuild algorithm to use the new wrapper

**Comment by tamir321** [comment]
tested on 

systemVersion: "v1.3.130",
fullSystemVersion: "v1.3.130-1601470196131",
