### ISSUE TITLE
algorithm "get from cache" should be prior to "get from peer"

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#908]
**HKube micro-service**
worker

**Describe the bug**
the algorithm should check if the data needed is in cached before reaching to get the data from peer 
- [x] python
- [x] java
- [x] node

**Comment by maty21** [comment]
fixing it will fix  #912 also therefore I'm closing it

**Comment by yehiyam** [comment]
@golanha @NassiHarel Can this issued be moved to QA?

**Comment by NassiHarel** [comment]
@yehiyam Yes
