### ISSUE TITLE
download node result (if it contains more then 1 MB ) should perform the same as download pipeline result

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#910]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
download node result (if it contains more then 1 MB ) should perform the same as download pipeline result 
the node download download the full result 
the pipeline download write message: "message":"data too large (10 MB), use the stream api"}}

**Comment by NassiHarel** [comment]
@tamir321 
It cannot perform the same, 
for node result, we already use the `stream api`.
for pipeline result, we added the zip as you suggested.

**Comment by tamir321** [comment]
tested on version

systemVersion: "v1.3.130",
fullSystemVersion: "v1.3.130-1601470196131",
