### ISSUE TITLE
java - DataAdapter - Timeout trying to get output causing the pipeline to pause 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#913]
**HKube micro-service**
java wrapper

**Describe the bug**
when  the wrapper  get timeout receiving data from peer it did not continue to to take data from storage
LOG 
[DEBUG] 2020-08-24 06:32:49.290 [main] Main - debug logging enabled
[INFO ] 2020-08-24 06:32:49.293 [main] WrapperConfig - no config in classpath
[INFO ] 2020-08-24 06:32:49.293 [main] CommConfig - no config in classpath
[INFO ] 2020-08-24 06:32:49.294 [main] StorageConfig - no config in classpath
[INFO ] 2020-08-24 06:32:49.294 [main] FSConfig - no config in classpath
[INFO ] 2020-08-24 06:32:49.294 [main] S3Config - no config in classpath
[INFO ] 2020-08-24 06:32:49.387 [main] Wrapper - connecting to uri: ws://localhost:3000/?storage=v2&encoding=bson
[DEBUG] 2020-08-24 06:32:49.444 [main] Wrapper - javax.websocket.DeploymentException: Connection failed.
[INFO ] 2020-08-24 06:32:49.661 [ tyrus-jdk-client-2] Wrapper - connected to worker
[INFO ] 2020-08-24 06:32:51.889 [ tyrus-jdk-client-1] BSONEncoder - decode took 107 milliseconds
[INFO ] 2020-08-24 06:32:51.890 [ tyrus-jdk-client-1] Wrapper - got message from worker:initialize
[INFO ] 2020-08-24 06:32:51.893 [Thread-4] Wrapper - Sending message to worker: initialized
[INFO ] 2020-08-24 06:32:51.902 [Thread-4] BSONEncoder - encode took 7 milliseconds
[INFO ] 2020-08-24 06:32:51.907 [ tyrus-jdk-client-2] BSONEncoder - decode took 1 milliseconds
[INFO ] 2020-08-24 06:32:51.907 [ tyrus-jdk-client-2] Wrapper - got message from worker:start
[INFO ] 2020-08-24 06:32:51.908 [Thread-5] Wrapper - Sending message to worker: started
[INFO ] 2020-08-24 06:32:51.908 [Thread-5] BSONEncoder - encode took 0 milliseconds
[DEBUG] 2020-08-24 06:32:51.909 [Thread-5] Wrapper - Before fetching input data
[INFO ] 2020-08-24 06:32:51.933 [Thread-5] MSGPackEncoder - encode took 3 milliseconds
[WARN ] 2020-08-24 06:32:52.935 [Thread-5] DataAdapter - Timeout trying to get output from 10.233.69.175:9020

**Expected behavior**
execute the following pipeline:
```json
{
    "name": "benchmarkpythonJava",
    "nodes": [
        {
            "nodeName": "onearray",
            "algorithmName": "python-big-array-6g",
            "input": [
                "@flowInput.bufferSize",
                "@flowInput.objectSize"
            ]
        },
        {
            "nodeName": "two",
            "algorithmName": "java-big-array-1g",
            "input": [
                "#@onearray"
            ]
        }
    ],
    "flowInput": {
        "bufferSize": 100,
        "objectSize": 10000000
    },
    "experimentName": "main",
    "options": {
        "ttl": 3600,
        "batchTolerance": 80,
        "progressVerbosityLevel": "info"
    },
    "priority": 3
}


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by golanha** [comment]
Problem occurs when running in log level debug.
In this case we attempt to print out the algorithm input, which is very large and causes a memory problem.

**Comment by tamir321** [comment]
when working with data larger the 300M the java algorithm stuck
```{
    "name": "benchmarkpythonJava",
    "nodes": [
        {
            "nodeName": "onearray",
            "algorithmName": "python-big-array-6g",
            "input": [
                "@flowInput.bufferSize",
                "@flowInput.objectSize"
            ]
        },
        {
            "nodeName": "two",
            "algorithmName": "java-big-array-1g",
            "input": [
                "#@onearray"
            ]
        }
    ],
    "flowInput": {
        "bufferSize": 1,
        "objectSize": 300000000
    },
    "experimentName": "main",
    "options": {
        "ttl": 3600,
        "batchTolerance": 80,
        "progressVerbosityLevel": "info"
    },
    "priority": 3,
    "flowInputMetadata": {
        "metadata": {
            "flowInput.bufferSize": {
                "type": "number"
            },
            "flowInput.objectSize": {
                "type": "number"
            }
        },
        "storageInfo": {
            "path": "test-hkube/main:benchmarkpythonJava:62ortooy/main:benchmarkpythonJava:62ortooy"
        }
    },
    "jobId": "main:benchmarkpythonJava:62ortooy",
    "startTime": 1598941178141,
    "lastRunResult": {
        "timestamp": "2020-09-01T06:19:30.889Z",
        "status": "completed",
        "timeTook": 5.675
    },
    "types": [
        "raw"
    ]
}

**Comment by golanha** [comment]
Added log messages. Waiting for a reproduce
