### ISSUE TITLE
Writing to the system log the event of completion of pipeline execution

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#92]
As a Pipeline Builder/ HKube Manager I want that HKube will write to the system log of HKube, the event of completion of pipeline execution, so I'll be able to identify and diagnose the source of pipeline problems.
---
**User Story implementation details:**
The information written to the sytem log will include the following:
1. General pipeline details, see #89
2. Event description: completion of pipeline execution

**Comment by eytangro** [comment]
TID-120
