### ISSUE TITLE
Replying for the "get from peer" request  cause the algorithm to crash due to out of memory 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#921]
**HKube micro-service**
worker

**Describe the bug**
replying for the get from peer cause the algorithm to crash due to out of memory 

execute the following pipeline 
the "one" node  crash due to out of memory 
algorithm python-big-array-6g has disconnected while in ready state, reason: CLOSE_ABNORMAL. status: terminated,exitCode: 0,reason: OOMKilled,startedAt: 2020-08-31T11:15:19Z,finishedAt: 2020-08-31T11:15:43Z,containerID: docker://5f8cad0603a6c2ca655f25534925c7724ee29fb0f3f48ab3e90bb1b3a4a53746

```json
{
    "name": "benchmarkpython6",
    "nodes": [
        {
            "nodeName": "one",
            "algorithmName": "python-big-array-6g",
            "input": [
                "@flowInput.objectSize"
            ]
        },
        {
            "nodeName": "two",
            "algorithmName": "green-alg",
            "input": [
                "@one",
                "#[1...1000]"
            ]
        }
    ],
    "flowInput": {
        "objectSize": 399000000
    },
    "experimentName": "main",
    "options": {
        "ttl": 3600,
        "batchTolerance": 80,
        "progressVerbosityLevel": "info"
    },
    "priority": 3
}


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by NassiHarel** [comment]
@tamir321 
How much memory node `one` have?

**Comment by tamir321** [comment]
tested on 
systemVersion: "v1.3.130",
fullSystemVersion: "v1.3.130-1601470196131",
