### ISSUE TITLE
stopping node that contain the ETCD LEADER cased the HKUBE to stop working

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#927]
**HKube micro-service**

**Describe the bug**
I stop the node congaing the ETDC leader the system didn't recovered properly

**Comment by yehiyam** [comment]
Changed helm settings (https://github.com/kube-HPC/helm/commit/60b6fbe70ca43df8cf97088189999e9637102c86)

**Comment by tamir321** [comment]
tested on version
systemVersion: "v1.3.133",
fullSystemVersion: "v1.3.133-1601904627769",
