### ISSUE TITLE
deleted algorithm  are not deleted from the ETCD /algorithms/queue/

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#928]
**HKube micro-service**
ETCD cleaner

**Describe the bug**
deleted algorithm  are not deleted from the ETCD /algorithms/queue/

**Comment by NassiHarel** [comment]
@tamir321 
This should be auto-deleted, eventually...

**Comment by tamir321** [comment]
tested on 
systemVersion: "v1.3.130",
fullSystemVersion: "v1.3.130-1601470196131",
