### ISSUE TITLE
Writing to the system log the event of  receiving algorithm request

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#94]
As a Pipeline Builder/ a HKube Manager I want that HKube will write to the system log, the event of receiving algorithm request, so I'll be able to identify and diagnose the source of pipeline/ algorithm problems.
---
**User Story implementation details:**
The information written to the sytem log will include the following:
1. General pipeline details, see #89
2. Algorithm type
3. Event description: receiving algorithm request

**Comment by eytangro** [comment]
TID-120

**Comment by tamir321** [comment]
# event in log test

File: tid_140.js
describe : "HKUBE Logs elasticsearch"

Test | description 
------|----------------
TID_120 pipeline events in system log of Hkube (git 94 95 96 ) | execute pipeline and view event in log
