### ISSUE TITLE
Pipeline driver queue got stuck after ETCD disconnection

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#942]
**HKube micro-service**
Pipeline driver queue

**Describe the bug**
after receiving the following error "failed to store data to persistent storage, 14 UNAVAILABLE: Connection dropped" Pipeline driver queue got stuck
happened:
21.09.2020
16.09.2020
26.08.2020

**Comment by yehiyam** [comment]
Upgraded etcd package to include timeout on stuck requests. 
Need to monitor.

**Comment by tamir321** [comment]
happend again 27.09.2020

**Comment by yehiyam** [comment]
Updated ETCD client port to use 2379 and not 2380 (2380 is used for peer communication and 2379 should be used for client communication)
[helm commit](https://github.com/kube-HPC/helm/commit/f45bc737525bf7b4ff4fd9ac938e647e05168f39)

**Comment by tamir321** [comment]
tested for 4 days 
on version 
systemVersion: "v1.3.130",
fullSystemVersion: "v1.3.130-1601470196131",
