### ISSUE TITLE
Writing to the system log the event of  finish the execution of algorithm request

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#96]
As a Pipeline Builder/ a HKube Manager I want that HKube will write to the log of the pipeline, the event of finish the algorithm execution, so I'll be able to identify and diagnose the source of pipeline/ algorithm problems.
---
**User Story implementation details:**
The information written to the sytem log will include the following:
1. General pipeline details, see #89
2. Event description: finish the execution of algorithm request including the return code of the algorithm (e.g. success/ failure).

**Comment by eytangro** [comment]
TID-120

**Comment by tamir321** [comment]
# pipeline and algorithm events in system log

File: tid_140 .js
describe: "HKUBE Logs elasticsearch"

Test | description 
------|----------------
 TID_120 pipeline events in system log of Hkube (git 94 95 96 )| validate logs in elasticsearch
