### ISSUE TITLE
Debug url does not contain ingress prefix

### ISSUE THREAD

**Issue by yehiyam** [kube-HPC/hkube#961]
**HKube micro-service**
api-server
**Describe the bug**
when hkube is installed with non-default url prefix ( i.e. `/some-prefix/hkube/dashboard` ) the debug URL shown in the dashboard does not contain the prefix: `ws://server/hkube/debug/alg`

**Expected behavior**
The debug url should be 
`ws://server/some-prefix/hkube/debug/alg`

**To Reproduce**
1. install hkube with global.ingress.prefix value set
2. add debug worker
3. check the debug url

**Comment by tamir321** [comment]
tested on version

systemVersion: "v1.3.133",
fullSystemVersion: "v1.3.133-1601904627769",
