### ISSUE TITLE
node algorithm cant work with data larger then 1G 

### ISSUE THREAD

**Issue by tamir321** [kube-HPC/hkube#968]
**HKube micro-service**
To which micro-service the bug related to, `Dashboard` ,`Monitor-Server` etc.

**Describe the bug**
when trying to work with data larger than 1G getting error 
node: ../../nan/nan.h:890: Nan::MaybeLocal<v8::Object> Nan::NewBuffer(char*, size_t, node::Buffer::FreeCallback, void*): Assertion `length <= imp::kMaxLength && "too large buffer"' failed.
Info
1111/10/20 09:15:14Abo

**Comment by yehiyam** [comment]
zmq nodejs 5.x uses [nan](https://github.com/nodejs/nan) for the binding to c++. nan has a limitation 1GB when allocating node `Buffer` objects.
zmq nodejs 6.x (which is in beta for now) uses [NAPI](https://nodejs.org/api/n-api.html) which allows the maximum size of Buffer in node (in node 14.8.0 it is `MAX_LENGTH: 4294967295`, or 4GB)
