### ISSUE TITLE
Writing internal algorithm information to the system log

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#97]
As a Pipeline Builder I want that HKube will enable the algorithm to add internal information to the sytem log, so I'll be able to identify and diagnose the source of pipeline/ algorithm problems.
---
**User Story implementation details:**
The information written to the system log will include the following:
1. General pipeline details, see #89
2. Event description: internal algorithm information

**Comment by eytangro** [comment]
TID-140
