### ISSUE TITLE
Cannot use python code that needs to be installed as a package

### ISSUE THREAD

**Issue by brainoom** [kube-HPC/hkube#972]
**HKube micro-service**
No idea. creating an algorithm

**Describe the bug**

Cannot use a python algorithm that needs to be installed.
When writing a python package, the best practice is to have something that 
can be installed with `pip install .` that should trigger the requirements installation.
When the code is structured as `package` instead of as `script` it cannot be run without
installing, because of issues like import locations (You should do a `dev install` to use it)

**Expected behavior**
To have an option for choosing the "setup command" for my algorithm

**To Reproduce**
Try to add this:
https://github.com/brainoom/hktest
let me know to whom should I give access.
Maybe it is related to which files are packed in the zip?

**Comment by brainoom** [comment]
in #974

**Comment by yehiyam** [comment]
tracked in https://github.com/kube-HPC/hkube/issues/1080
Closing
