### ISSUE TITLE
Monitor handling time of pipeline request

### ISSUE THREAD

**Issue by Ronenk5678** [kube-HPC/hkube#98]
As a Pipeline Builder/ HKube manager I want to be able to view statistics of pipeline request's handling time, so that I can monitor the performance of pipeline execution .

**User Story implementation details:**
1. Handling time of pipeline's requests - from the time the pipeline's request was received till the time the result of the pipeline is sent to the user.
2. Statistics of pipeline request's handling time  - 50 & 90 percentile of pipeline request's handling time 
3. Each of the statistics information will be calculated separately per pipeline type.
4. Graph view is detailed in #102

**Comment by eytangro** [comment]
TID-201
