### ISSUE TITLE
Improve algorithms versions

### ISSUE THREAD

**Issue by NassiHarel** [kube-HPC/hkube#998]
- [x] each algorithm change should create a new version (unless there is a new build, so the new version will be after the build)
- [x] if the algorithm version changed during run with force=true, the pipeline should fail.
- [ ] if the algorithm version changed, should we need to kill jobs????
- [x] each version has now a unique id, semver, created date.
- [ ] there is a new trigger for build (baseImage), triggers are 'checksum', 'env', 'commit', 'baseImage'.
- [ ] you can now trigger build without any change, just use `forceBuild: true`.
- [ ] you can now override the current algorithm data. just use `forceUpdate: true`.
- [ ] each build will have a unique imageTag.
- [x] there is an option to tag algorithm version (add labels, make it pinned)

**Comment by tamir321** [comment]
#  algorithm version test

File:algorithm_test.js 
describe: "Test Algorithm Version"

Test | description 
------|----------------
algorithm change creates a new version | create an algorithm from image add algorithmEnv validate that a new version created
algorithm change creates a new version CPU |  create an algorithm from image add change CPU to 2 validate that a new version created
update algorithm nodeSelector | create algorithm with hot worker and nodeSelector create new version with different nodeSelector validate that the pod change to the node
